navikt/familie-ef-soknad-frontend

.circleci/config.yml, .prettierignore, .prettierrc, README.md, craco.config.js, nais.config.yaml, package-lock.json, package.json, public/manifest.json, server.js, src/App.tsx, src/index.less, src/innsending/api.ts, src/komponenter/Soknad.tsx, src/serviceWorker.js, src/setupProxy.js, src/utils/dato.ts, tsconfig.json
Innhold i PR: 
* [be-pretty](https://github.com/capaj/be-pretty) - reformattering av all kode ved commit. 
* Oppdatert readme med instrukser på hvordan du kan sette opp [Prettier](https://github.com/capaj/be-pretty) til å reformattere koden din når man lagrer filen i IntelliJ 😌 ✌️ 
_____
Prettier er en _code formatter_ som er et utmerket verktøy for å holde koden ren og konsis i et delt repo. Verktøyet sørger for at du som utvikler kan copy paste kode som du vil uten å måtte trenge å "tabbe" for å flytte koden på riktig plass, at semi kolon alltid blir lagt på slutten av en linje og at white spaces blir lagt til på de riktige stedene. Man kan konfigurere enda mer hvordan man vil at Prettier skal håndheve code cleaningen i `.prettierrc`.
Settes det opp lokalt i intellij trenger du aldri å …
=> Prettier setup

package-lock.json, package.json, src/språk/LocaleTekst.tsx
- ❌ react-intl har nå egen typedefinisjoner. Som et resultat er @types/react-intl deprecated og fjernet fra vår app. 
- 👩‍🔧  LocaleTekst er tweaket til å passe ny minor versjon av react-intl. 
✨
=> Oppdaterer og tilpasser kode til ny versjon av react-intl

src/components/dato/Datovelger.tsx, src/context/SøknadContext.tsx, src/models/person.ts, src/søknad/steg/2-bosituasjon/Bosituasjon.tsx, src/søknad/steg/2-bosituasjon/OmSamboerenDin.tsx, src/søknad/steg/2-bosituasjon/SøkerSkalFlytteSammenEllerFåSamboer.tsx
**Denne PR-en er resultatet av en parprogrammeringsdag med Espen Hellerud som sitter på Digipost, og bruker React Context & Hooks daglig 😄** 
Var så heldig å få låne han en hel dag til å stille masse spørsmål, kvalitetsjekke koden vår og få input på forbedringer vi kunne gjøre 👩‍💻 👨‍💻  
**Inneholder:**
- En mer simpel context med kun useState
- Mindre nøstede funksjoner for å sette Bosituasjon inn i søknad vha av en lokal useState funksjon. 
- I stedet for å ha resette Bosituasjonsobjektet i en useEffect, så gjør vi det når bruker trykker på en knapp / et nytt svarsalternativ. And it feels so right ✨ 
Refaktorerte Bosituasjon fordi det ikke er et så stort steg, en tanken er vel å fortsette å kode/refaktorere de andre stegene i dette mønsteret.
Ta det litt etter hvert når vi får mulighet …
=> Refaktorering av Bosituasjon

src/helpers/barn.ts, src/language/tekster.ts, src/mock/person.json, src/models/barn.ts, src/models/forelder.ts, src/models/person.ts, src/søknad/steg/1-omdeg/personopplysninger/Personopplysninger.tsx, src/søknad/steg/3-barnadine/BarnaDine.tsx, src/søknad/steg/3-barnadine/BarneConfig.tsx, src/søknad/steg/3-barnadine/LeggTilBarn.tsx, src/søknad/steg/4-barnasbosted/AnnenForelderKnapper.tsx, src/søknad/steg/4-barnasbosted/BarnasBostedHeader.tsx, src/søknad/steg/4-barnasbosted/BarnetsBostedEndre.tsx, src/søknad/steg/4-barnasbosted/BarnetsBostedLagtTil.tsx, src/søknad/steg/4-barnasbosted/BostedOgSamvær.tsx, src/søknad/steg/4-barnasbosted/OmAndreForelder.tsx, src/søknad/steg/4-barnasbosted/SkalBarnBoHosDeg.tsx, src/utils/søknad.ts
- [Utvider søknadsfelter for barnesteg ](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-852)med `{spørsmålid og svarid}` der spørsmål med svar som senere skal trigge et dokumentasjonsbehov. 
- Inneholder noen småfixes der svar ikke blir ordentlig satt pga. endringer til spørsmålskomponenter
- Har flyttet IForelder og IBarn til egne ts-filer :)
=> Utvider søknadsfelter for barnesteg (3 og 4)

package-lock.json, package.json, src/søknad/forside/Forside.less, src/søknad/forside/Forside.tsx, src/søknad/steg/3-barnadine/BarnaDine.tsx
Henter forsideinformasjonen fra Sanity. Planen først var å la hele siden være ett tekstelement, der man kunne legge inn overskrifter, lenker, bullet-points og alt man trenger under ett felt, men jeg fikk ikke riktig spacing mellom seksjonene på denne måten, så ble det også litt uryddig slik.
Sideelementene er derfor organisert på denne måten (disse endringene er gjort i `family-soknad-sanity`): ![Screen Shot 2020-04-17 at 12 18 54 PM](https://user-images.githubusercontent.com/1413265/79569063-3f719400-80b7-11ea-8f1a-a38ed2825f78.png), der hver seksjon inneholder en valgfri tittel + innhold, slik: 
Støtter ikke internasjonalisering nå, usikker på hvordan vi skal løse det. Kan jo kjøre tre felter for tittel og tre for innhold, men følte det ble litt uryddig her. Kanskje det er eneste måten …
=> Intro sanity

src/arbeidssøker/Forside.tsx
Ny side for arbeidssøker-skjemaet.
Vi bruker arbeidssøker-branchen som "master" for det nye skjemaet, og brancher ut herfra når vi legger til nye features.
=> Hent forside for arbeidssøker

src/arbeidssøker/ArbeidssøkerApp.tsx, src/arbeidssøker/Forside.tsx, src/arbeidssøker/Spørsmål.tsx
La til mulighet for å gå til spørsmålssiden fra forsiden. Hardkodet pathen til spørsmålssiden slik: `onClick={() => history.push('/arbeidssøker/spørsmål')}`, men kanskje vi må legge til en Routes-fil her også for at det skal bli riktig i Side-komponenten, da den legger til forrige og neste-knapper.
=> Gå videre til neste steg fra Forside

src/arbeidssøkerskjema/SkjemaApp.tsx, src/arbeidssøkerskjema/SkjemaContext.tsx, src/arbeidssøkerskjema/side/Side.tsx, src/arbeidssøkerskjema/steg/1-Spørsmål.tsx, src/arbeidssøkerskjema/steg/2-Oppsummering.tsx, src/arbeidssøkerskjema/steg/3-Kvittering.tsx, src/arbeidssøkerskjema/typer/skjema.ts
- Siden vi skal hente fnr direkte fra innlogget bruker, så fjerner vi fødselsnr feltet i skjemaobjektet.  Da trenger vi ikke en ISkjema datamodell. Bruker IArbeidssøker direkte. 
- Skifter til å bruke useIntl hook
✨ 🐈
=> Endrer fra ISkjema til IArbeidssøker++

src/language/tekster.ts, src/models/forelder.ts, src/models/steg/barnasbosted.ts, src/søknad/steg/4-barnasbosted/AnnenForelderKnapper.tsx, src/søknad/steg/4-barnasbosted/BarnetsBostedEndre.tsx, src/søknad/steg/4-barnasbosted/BarnetsBostedLagtTil.tsx, src/søknad/steg/4-barnasbosted/ForeldreConfig.tsx, src/søknad/steg/4-barnasbosted/OmAndreForelder.tsx, src/søknad/steg/4-barnasbosted/ikkesammeforelder/BorAnnenForelderISammeHus.tsx
Setter defaultverdien til `kanIkkeOppgiAnnenForelderFar` til false, og gjør følgende variabelnavnendringer:
borISammeHus -> borAnnenForelderISammeHus
hvordanBorDere -> borAnnenForelderISammeHusBeskrivelse
=> Fiks variabelnavn

src/søknad/steg/2-bosituasjon/OmSamboerenDin.tsx
Navn og personnummer manglet label på samboerDetaljer (verdien lå rett på rot). Denne fikser dette.
=> Legg til label på samboerDetaljer

src/components/gruppe/PersonInfoGruppe.tsx, src/søknad/steg/6-meromsituasjon/FåttJobbTilbud.tsx, src/søknad/steg/6-meromsituasjon/MerOmDinSituasjon.tsx
**Inneholder de fleste fiksene i [dette Favro-kortet](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1289) :**
NB! Mangler å fikse der det brukes `<PeriodeDatovelger/>`. Denne bør fikses i en egen PR. 🤓
=> Nullstilling av tilstand i søknadsdialogen

src/søknad/steg/3-barnadine/BarnaDine.tsx, src/søknad/steg/4-barnasbosted/BarnasBosted.tsx
- Hvis man går tilbake for å endre informasjon om barna sine, vil man få en "neste"-knapp i stedet for "tilbake til oppsummering" siden de da må fylle ut informasjon om den nye forelderen hvis man skulle legge til et nytt barn. 
- Løser at man slipper å fylle ut "første" barn i lista på nytt (hvis forelder allerede eksisterer), men at man heller må fylle ut info til den nye forelderen som er lagt til.
=> Neste fremfor tilbake til oppsummering

src/language/tekster.ts, src/søknad/steg/4-barnasbosted/BarnetsBostedEndre.tsx
'Barn med termin XX.XX.XXXX' vises bare på knappene for å velge annen forelder og under storken.
=> 'Barnets andre forelder' skal vises når man legger til barnet

src/language/tekster.ts, src/søknad/steg/4-barnasbosted/SkalBarnetBoHosSøker.tsx, src/søknad/steg/5-aktivitet/FåttJobbTilbud.tsx, src/søknad/steg/5-aktivitet/aksjeselskap/Aksjeselskap.tsx
Oppdaterer tekster i henhold til innholdsdokumentet. De ferskenfargede tekstene som hadde ID er endret. Noen tekster (som fødselsnummer / d-nummer) ser ut til å være fikset i andre oppgaver, så disse er ikke gjort noe med (de er fortsatt ferskenfargede i innholdsdokumentet).
=> Oppdater tekster

src/søknad/steg/5-aktivitet/Aktivitet.tsx, src/søknad/steg/6-meromsituasjon/MerOmDinSituasjon.tsx, src/søknad/steg/7-oppsummering/OppsummeringAktiviteter.tsx, src/søknad/steg/7-oppsummering/OppsummeringBarnaDine.tsx, src/søknad/steg/7-oppsummering/OppsummeringBarnasBosituasjon.tsx, src/utils/visning.tsx
For at React skal kunne oppføre seg forutsigbart må vi ha _key_ på alle elementer som rendres som lister
=> Key på alle liste-elementer i React

src/components/dato/Datovelger.tsx
For ubegrensede datovelgere, settes maksgrensen til dagens dato + 100 år, og mingrensen til dagens dato - 200 år.
Unngår at man skriver inn år 8490332, som kan føre til at ting kræsjer pga. ugyldig format.
=> Sett maksgrense og mingrense på alle datovelgere

src/models/søknad.ts, src/søknad/steg/1-omdeg/personopplysninger/Personopplysninger.tsx, src/søknad/steg/1-omdeg/personopplysninger/PersonopplysningerConfig.tsx
Steg 1 - Resett svar om sivilstatus og medlemskap hvis søker velger "Nei" på spørsmål "Bor søker på registrert adresse?" etter å ha besvar spørsmål en gang. 
Dette er for at søknadsobjektet skl holde seg oppdatert etter det brukeren gjør, og tvinge bruker til å fylle ut felter/besvare spørsmål på nytt som en del av valideringen.
=> Steg 1 - Resett felter hvis søker velger "Nei" på spørsmål "Bor søker på registrert adresse?" 

src/helpers/steg/forelder.ts
Saken som er meldt: https://jira.adeo.no/browse/FAGSYSTEM-126647
**CASE:** 
Søker har minst 2 barn. 
Fyll inn informasjon på første barnet. 
Velg "Samme som barn1". 
Velg så disse svarsalternativene til spørsmålene under: 
**Spm:** "Har annen forelder samvær med Barn?"
**Alt:** "Ja, men ikke mer enn vanlig"
**Spm:** "Har dere skriftlig samværsavtale?"
**Alt:** "Ja, men beskriver ikke ... " ELLER "Nei"
Sjekk om søker får opp "Neste" knapp slik at de kan gå videre i søknaden.
=> Bugfix/Barnas bosted og foreldresamvær -  Bruker kan ikke gå videre i søknad

src/søknad/steg/8-dokumentasjon/LastOppVedlegg.tsx
Fjern visning av  avhukingsalternativ "Jeg har sendt inn denne dokumentasjonen til NAV tidligere" for dokumentasjonsbehovet "Faktura for barnepassordning"
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2312
**Ser ut sånn her nå:**
=> Barnetilsyn - Fjern visning av avhukingsalternativ for dokbehov "faktura Barnepass"

src/barnetilsyn/BarnetilsynContext.tsx, src/barnetilsyn/steg/5-aktivitet/Aktivitet.tsx, src/context/SøknadContext.tsx, src/helpers/tommeSøknadsfelter.ts, src/models/søknad/søknadsfelter.ts, src/overgangsstønad/steg/5-aktivitet/Aktivitet.tsx, src/overgangsstønad/steg/6-meromsituasjon/MerOmDinSituasjon.tsx, src/utils/spørsmålogsvar.ts
ref dette [kortet](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2602)
- Legg til alternativer i ISpørsmålListeFelt slik at det blir lettere å vite hva bruker har svart på i pdfen. 
(`verdi` er de valgte svarsalternativene, mens `alternativer` er alle tilgjengelige svarsalternativer.)
=> Utvid ISpørsmålListeFelt til å ha svarsalternativer

src/søknad/steg/4-barnasbosted/AnnenForelderKnapper.tsx
Løser denne [Favro-oppgaven](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-3027) ved å nullstille foreldreinformasjonen når man velger "Annen forelder".
=> Nullstill foreldreinfo

src/language/tekster_nb.ts
Er en gammel fiks som tydeligvis har blitt reversert, endrer tilbake til "Donor".
=> Endre tekst fra 'Donorbarn' til 'Donor'

src/søknad/forside/Forsideinformasjon.tsx
Viser `We are in the process of translating this application. The few missing translations will show up in Norwegian until we've translated them.` om man velger engelsk.
=> Legg til advarsel om at ikke alle tekster er oversatt

src/components/dato/Datovelger.tsx, src/utils/dato.ts
Hindrer at man får sendt inn søknad med dato på format `mm.dd-yyyy`, som kræsjer backend.
=> Fiks datoformat

src/barnetilsyn/Forside.tsx, src/overgangsstønad/Forside.tsx, src/skolepenger/Forside.tsx, src/søknad/forside/FortsettSøknad.tsx
Hvis man fortsetter en påbegynt søknad, vil det i amplitude se ut som man faller av etter Forsiden. Vi unngår å logge sidevisning på Forsiden i disse tilfellene.
Har også lagt på logging på "Fortsett mellomlagret søknad"-siden.
=> Mer amplitude-logging

src/App.tsx, src/barnetilsyn/BarnetilsynApp.tsx, src/skolepenger/SkolepengerApp.tsx, src/utils/amplitude.ts
Legger til riktig adressesperre-feilmelding på sidene for barnetilsyn og skolepenger, i tillegg til å logge dette til amplitude.
=> Fiks adressesperre

src/components/dato/Datovelger.tsx, src/helpers/steg/forelder.ts, src/søknad/steg/4-barnasbosted/BarnetsBostedEndre.tsx
**Innhold:**
- Filtrer bort/Ikke vis neste seksjoner (utfylt eller ikke) dersom man har feil fdato. Vil også skje dersom bruker går opp og tilbake for å endre fdato. Skal ikke gå an å fylle ut kun et årstall. 
- Ikke vis Neste knapp (Neste barn) hvis man har feil format på fdato
- Legg til rette for at bruker kan fjerne dato i etterkant (dvs. at feltet blir en tom streng) og fremdeles gå videre (siden fdato er optional).
Note to self: Vurder å endre "Neste" (barn) til noe annet mtp UU. Er forvirrende for bruker å "høre" to Neste knapper. 
Forslag til erstatningstekst? 
- "Lagre informasjon" 
- "Gå videre til neste barn" / "Gå videre" *lagre infoen, vis neste knapp nederst*
..? 
**Favro-kort med screenshots:** https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd? …
=> Ikke la bruker gå videre med dato i feil format

src/helpers/steg/forelder.ts, src/søknad/steg/4-barnasbosted/BarnetsBostedEndre.tsx
Fiksen der vi prøvde å være strenge slik at bruker måtte fylle ut årstall (dersom annen forelder ikke fantes i folkeregisteret) sjekket bare `forelder` som er objektet for når man svarer på spm og fyller inn forelder info i søknadsdialogen. Når man henter forelder fra pdl lagres den i `medforelder`, så her har det endt med en glipp der bruker ikke kan gå videre hvis de har forelder hentet fra pdl. 
Denne PRen skal fikse dette ved å sjekke medforelder i tillegg. 😎
=> Sjekk medforelder

src/helpers/steg/forelder.ts
Denne fikser feilen som gjør at man kan sende inn med manglende felter, men etterlater en mindre alvorlig bug (brukeren får flere "Annen forelder"-knapper enn nødvendig i tilfeller der flere barn har samme forelder).
=> Foreløpig fiks

src/helpers/steg/omdeg.ts, src/mock/mockPersonUtenBarn.json
Fikser en bug der man kan gå videre i søknadsdialogen på steg 1 dersom man er gift og skriver inn et årstall under "datoSøktSeparasjon".
=> My og Tor fikser bugs - søktSeparasjon datovelger årstall

src/søknad/steg/4-barnasbosted/AnnenForelderKnapper.tsx, src/søknad/steg/4-barnasbosted/BarnetsBostedLagtTil.tsx
Løser [denne](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-6154) oppgaven. Man fikk muligheten til å klikke "Endre informasjon" på det neste barnet før man hadde fylt ut nåværende. Denne feilen oppsto etter at vi gjorde en endring på barnekortene slik at vi fyller ut forelder-objektet med en gang, og kan derfor ikke lenger sjekke om forelder er fylt ut ved å bare sjekke om forelder ikke er null.
Løses ved at man bare viser kortet om også det obligatoriske spørsmålet "Bor Xs andre forelder i Norge" er besvart.
=> Ikke vis "Lagt til"-barn før man har svart på spørsmål om forelder

src/søknad/steg/2-bosituasjon/OmSamboerenDin.tsx, src/søknad/steg/4-barnasbosted/OmAndreForelder.tsx
Siden identen ikke er oppdatert i valideringsfunksjonen, gjorde dette at feil fødselsnummer ble satt. Løser [denne oppgaven](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-5866).
=> Fjern oppdatering av state fra validering

src/arbeidssøkerskjema/Forside.tsx, src/mock/mockToggles.json, src/models/søknad/toggles.ts, src/søknad/forside/Forsideinformasjon.tsx
Fjern toggle som ikke er i bruk:
visSkalBehandlesINySaksbehandling = "familie.ef.soknad.visSkalBehandlesINySaksbehandling"
Fjern toggle som har vært skrudd på i prod lenge:
vis_språkvelger = 'familie.ef.soknad.sprakvelger'
=> Rydding i toggles:

src/søknad/steg/5-aktivitet/arbeidsforhold/Arbeidsgiver.tsx
Dette gjør at man ikke kommer videre i søknaden dersom man har fjerna svar på "Hvor mye jobber du?" etter at man har svart på spørsmålet om ansettelsesforhold. [Favro-oppgave](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2777).
=> Fjern svar på neste spørsmål dersom svar på 'Hvor mye jobber du?' fjernes

src/models/søknad/toggles.ts, src/søknad/steg/1-omdeg/sivilstatus/begrunnelse/SøknadsBegrunnelse.tsx, src/søknad/steg/2-bosituasjon/OmSamboerenDin.tsx, src/søknad/steg/4-barnasbosted/OmAndreForelder.tsx
Sletter ident dersom den blir ugyldig etter å ha vært gyldig. Se disse Favro-oppgavene: [Skriv om Fnr/navn-komponenten](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8010) og [Samboerdetaljer - Validering feiler hvis man går tilbake og sletter Fnr/ident slik at det sendes som null til backend](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-3281).
=> Slett Fnr-state dersom den blir ugyldig

src/components/dato/ÅrMånedvelger.tsx
Denne sjekken har alltid blitt false før, da objektene aldri vil være de samme (siden javascript sammenligner objektet ved referanse og ikke verdi). Dette har likevel gått bra til nå, siden 'begrensninger'-objektet aldri har vært tomt til nå.
Det var den nye versjonen av [TypeScript som fanget dette opp](https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/).
=> Fiks sjekk av tomt objekt

src/arbeidssøkerskjema/steg/3-Kvittering.tsx, src/søknad/steg/1-omdeg/personopplysninger/SøkerBorIkkePåAdresse.tsx, src/søknad/steg/9-kvittering/ErklæringSamlivsbrudd.tsx, src/søknad/steg/9-kvittering/RegistrerDegSomArbeidssøker.tsx, src/søknad/steg/9-kvittering/SykSøker.tsx, src/søknad/steg/9-kvittering/SyktBarn.tsx, src/søknad/steg/9-kvittering/TilleggsstønaderArbeidssøker.tsx, src/søknad/steg/9-kvittering/TilleggsstønaderHarAktivitet.tsx, src/søknad/steg/9-kvittering/TilleggsstønaderUnderUtdanning.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10353
Fjerner wrap av KomponentGruppe då den legger til padding-bottom som ikke trengs for lenkene 
Før:
Etter:
=> Endret lenke med link fra nytt designsystem

src/søknad/steg/5-aktivitet/underUtdanning/Studiekostnader.tsx
`type={'number'}` er visst dårlig på håndtering av størrelser hvis ikke denne settes eksplisitt. 
**Før:**
**Etter:**
=> Skal sette størrelse på inputfelt utgifter til skolepenger

src/language/tekster_en.ts, src/language/tekster_nb.ts, src/language/tekster_nn.ts, src/søknad/steg/1-omdeg/medlemskap/Medlemskap.tsx
**Hvorfor:** 
Vil ikke vise fram varsel med feil info hvis dette er eøs-opphold. 
**Dette er steg 1:** 
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12182
https://nav-it.slack.com/archives/G0104QDKZJQ/p1678981141770259
**Neste steg:** 
Analysere behov - trenger vi mer info? Eller kan vi fjerne hele spørsmålet, eller er det greit slik? Bedre infotekst? 
**Endring i ui:**
=> Fjern advarsel opphold

package-lock.json, package.json, src/assets/KalenderIkonSVG.tsx, src/components/språkvelger/SpråkSelectMenu.tsx, src/components/språkvelger/Språkvelger.tsx, src/index.tsx, src/language/LocaleTekst.tsx
Ting ser "helt likt" ut som tidligere. Oransje og blåfargen som er tatt i bruk er akk samme fargekode. Fant ikke den grå, men er såpass lite forskjell på den nye og den tidligere at jeg ikke tror noen ser forskjell😅
`nav-frontend-core` kan ikke slettes fordi den påvirker veldig mye av css-en. La den derfor til i index.tsx så flere skal slippe å slette den ved en feil🙃
=> Ta i bruk farger fra ds-tokens

package-lock.json, package.json, src/components/dato/Datovelger.tsx, src/components/dato/PeriodeDatovelger.tsx, src/components/dato/ÅrMånedvelger.tsx, src/components/spørsmål/SelectSpørsmål.tsx, src/language/tekster_en.ts, src/language/tekster_nb.ts, src/language/tekster_nn.ts, src/models/steg/omDeg/medlemskap.ts, src/models/søknad/søknadsfelter.ts, src/søknad/steg/1-omdeg/medlemskap/Medlemskap.tsx, src/søknad/steg/1-omdeg/medlemskap/MedlemskapConfig.tsx, src/søknad/steg/1-omdeg/medlemskap/PeriodeBoddIUtlandet.tsx, src/søknad/steg/1-omdeg/medlemskap/Utenlandsopphold.tsx
[FAVRO](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12261)
Søknad skal inneholde to nye felter for å registrere hvilket land søker oppholder seg i nå (`oppholdsland`) og hvilket land de oppholdt seg under et utenlandsopphold (`land`).
- Lagt til et nytt type spørsmål `SelectSpørsmål`
- Endret logikken for hvordan spørsmål vises
- Man skal få opp spørsmålet om man har utenlandsopphold dersom svaret er "Ja" på at man oppholder seg i Norge, eller man har valgt et land ved "Nei" på opphold. 
- Tatt i bruk [land-verktoy](https://github.com/navikt/land-verktoy) for å hente liste med land. 
- Her kan man sende inn "nb" eller "en" (ikke nn). 
- Lagd egne tester for mapping av feltene i api
- Lastet opp i preprod og sjekket at feltene følger med til …
=> Landvelger i søknad 

src/arbeidssøkerskjema/steg/1-Spørsmål.tsx, src/language/tekster_en.ts, src/language/tekster_nb.ts, src/language/tekster_nn.ts, src/søknad/steg/5-aktivitet/arbeidssøker/Arbeidssøker.tsx, src/søknad/steg/5-aktivitet/arbeidssøker/ArbeidssøkerConfig.ts
[FAVRO](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-11521) 
Vi ønsker å vise en feilmelding ved spørsmål hvor trykk på "nei" fører til at man ikke kan motta stønad.
Spørsmål om man kan starte innen en uke: 
Spørsmål om man ønsker å registreres som arbeidssøker for minst 50% jobb:
=> Skal vise alert ved trykk på nei for arbeidssøker begynne om en uke

src/components/filopplaster/Filopplaster.css, src/components/filopplaster/Filopplaster.tsx, src/components/filopplaster/OpplastedeFiler.tsx, src/language/tekster_en.ts, src/language/tekster_nb.ts, src/language/tekster_nn.ts
Etter at dokumentasjonsbehov ble rammet inn i et `GuidePanel` ble det litt trangere og listen med opplastede dokumenter litt stygg 🥲 [PR 1327](https://github.com/navikt/familie-ef-soknad/pull/1327)
Skrevet om koden så det så penere ut. Dette innebar f.eks. å bruke ikoner og knapper fra aksel og slette masse css. 
Har også gjort at det står "delete" om man har valgt engelsk. 
| Før      | Etter |
| ----------- | ----------- |
| <img width="561" alt="image" src="https://github.com/navikt/familie-ef-soknad/assets/46678893/a6610a15-177d-42c7-81a5-51b0dd14809d"> | <img width="561" alt="image" src="https://github.com/navikt/familie-ef-soknad/assets/46678893/da1afced-35c4-4588-8945-948754dff584">
|
=> 💄 Styling og refaktorering av Opplastede vedlegg

src/components/filopplaster/OpplastedeFiler.tsx
Glemte å legge med onClick for å fjerne opplastede dokumenter i PR #1351
=> Skal slette fil trykk på knapp

src/components/filopplaster/OpplastedeFiler.tsx
Opplastede dokumenter var stygg på mobil 😢 
Resultat: 
Mulig `size="small` blir litt lite på desktop, venter på svar fra Lars:
=> Skal vise frem filnavn penere på mobil

src/overgangsstønad/steg/4-barnasbosted/BarnasBosted.css
Annen forelder knapper ser ikke bra ut på mobil 😟 
**Før**
<kbd>
</kbd>
**Etter**
<kbd>
</kbd>
**Før**
<kbd>
</kbd>
**Etter**
<kbd>
</kbd>
=> Styling av Andre Forelder knapper mobil 📱 

Dockerfile
Chainguard har fjernet node 18 😢
=> Skal bruke gcr distroless node 18

src/barnetilsyn/steg/7-oppsummering/Oppsummering.tsx, src/overgangsstønad/steg/7-oppsummering/Oppsummering.tsx, src/utils/amplitude.ts
Forsatt mange warnings i søknad 😢 
Nå har målet vært å fjerne alle `any` i amplitude.ts. Noen steder er det bare fjernet mulighet for å sende inn flere props enn de som er definerte ordentlig (fordi det ikke ble brukt), mens andre steder er det definert ordentlig.
=> Skal unngå bruk av any i amplitude

src/barnetilsyn/Forside.tsx, src/skolepenger/Forside.tsx, src/utils/dato.ts
Ønsker kun å vise infoboks på barnetilsyn og skolepenger i perioden 1. mai til 31. august, har derfor gjort slik at infoboks kun vises i denne perioden.
- Årstallet i infoboksen er også endret til å være dynamisk i stedet for hardkodet.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-15276
=> Skjule infoboks

.github/dependabot.yml
Grupperer avhengigheter, en PR for major og en PR for minor og patch.
=> Dependabot: Grupperer avhengigheter

README.md, src/models/søknad/toggles.ts, src/overgangsstønad/steg/7-oppsummering/Oppsummering.tsx, src/utils/validering/validering.ts
Før fiks var det ikke mulig å legge inn vordende (personinformasjon om en du har planer om å gifte deg med) uten å legge inn fødselsdato på denne. Vi krever at du må legge inn enten fnr, eller fødselsdato tidligere. Her var ikke fnr godt nok vi godtok bare fødselsdato.
Prøvde først å gjøre dette med ett schema (som tiligere), men etter x antall forsøk ga jeg opp. Det er sikkert mulig hvis noen har lyst til å gi det et forsøk. 
Test i preprod: 
Alt ok - sender inn med fnr (dette fungerte ikke tidligere - klagde på at fødselsdato ikke var satt) 
Dato = feil
Både fnr og dato mangler: 
Skal ikke gifte seg = ok. 
Alt er feil
=> Validerbosituasjon oppsummering

nais-dev.yaml, nais-prod.yaml
Deploy vil krasje etter 18. desember uten denne endringen
=> Skal ha gyldig nais-template

src/barnetilsyn/BarnetilsynContext.tsx, src/helpers/steg/barnetsBostedEndre.ts, src/helpers/steg/forelder.ts, src/models/søknad/person.ts, src/søknad/steg/4-barnasbosted/BarnasBostedInnhold.tsx, src/søknad/steg/4-barnasbosted/BarnetsBostedEndre.tsx
- Gjort slik at informasjon om annen forelder fra gjenbruk ikke vises i oppsummering hvis den er død og ikke blir sendt med [Favro - oppgave 5](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-17705).
- Fikset slik at spørsmål om bor på samme sted må fylles ut selvom svar på annen forelder bor i Norge er nei.
- Skal ikke vise annen forelder knapp når det ikke skal være andre alternativer (barn).
Vi squasher ved merge, og lar console logger bli frem til merge.
=> Gjenbruk fikset opp i noen småfeil

src/barnetilsyn/BarnetilsynApp.tsx, src/barnetilsyn/BarnetilsynContext.tsx, src/barnetilsyn/steg/3-barnadine/BarnaDine.tsx, src/helpers/steg/barnetsBostedEndre.ts, src/helpers/steg/forelder.ts, src/models/steg/barn.ts, src/models/søknad/person.ts, src/søknad/steg/4-barnasbosted/AnnenForelderKnapper.tsx, src/søknad/steg/4-barnasbosted/BarnasBostedInnhold.tsx, src/søknad/steg/4-barnasbosted/BarnetsBostedEndre.tsx, src/utils/barn.ts, src/utils/søknad.ts, src/utils/typer.ts
Skal ikke ta med barn som er døde i ny søknad. Dette måtte fikses for gjenbruk. Dersom annen forelder har dødd siden forrige gang det ble søkt, skal annen forelder nullstilles.
Det er også forbedret logikk for at knapper som skal kopiere info fra annen forelder vises riktig. For at dette skulle bli greit å løse uten altfor mye kode ble det innført et flagg som sier om barn er hentet fra forrige søknad eller ikke.
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-17705
=> Ved gjenbruk skal ikke barn som er døde tas med i ny søknad

src/helpers/steg/barnetsBostedEndre.ts
Hvis en søker hadde flere enn ett barn og ønsket å søke om BT eller OS for disse var det ikke mulig å skrive/legge til noe om andre forelder på barn 2 og utover.
=> Fix andre forelder førstegangssøknad

src/barnetilsyn/BarnetilsynContext.tsx, src/helpers/steg/barnetsBostedEndre.ts, src/helpers/steg/forelder.ts, src/søknad/steg/3-barnadine/BarnaDineInnhold.tsx, src/søknad/steg/4-barnasbosted/BarnasBostedInnhold.tsx, src/søknad/steg/4-barnasbosted/BarnetsBostedEndre.tsx, src/utils/søknad.ts
Logikk for kopiering av barn med samme forelder tok ikke høyde for at barnetilsyn har noen spesifikke felter i søknad for den stønadstypen. Denne PR'n tar høyde for dette slik at kopiering av annen forelder virker.
=> Skal kunne kopiere barn i overgangsstønad

src/barnetilsyn/steg/7-oppsummering/Oppsummering.tsx, src/overgangsstønad/steg/7-oppsummering/Oppsummering.tsx, src/skolepenger/steg/6-oppsummering/Oppsummering.tsx, src/søknad/steg/7-oppsummering/OppsummeringBarnasBosituasjon.tsx
- Fjernet validering på aktivitet da den lagde mer trøbbel enn den var til hjelp med å finne mangler. 
- Viser kun barn som skal ha barnepass i oppsummering på 'Den andre forelderen og samvær'.
=> Fix på oppsummering BT gjenbruk

src/language/tekster_en.ts, src/language/tekster_nb.ts, src/søknad/steg/5-aktivitet/underUtdanning/StudieArbeidsmengde.tsx
Flyttet tekst som skal vises i alert ut i tekster. Har også laget engelsk versjon, slik at alerten bruker rett tekst basert på valgt språk.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-17920)
=> Tekst på alert prosent student  validering skal være på norsk og engelsk

src/barnetilsyn/BarnetilsynContext.tsx
Vil ikke vise fnr på annen forelder hvis informasjon om annen forelder er kopiert fra annet barn.
Denne fiksen fungerer så lenge annet barn fremdeles er relevant og med i søknaden.
Bilder viser før og etter hvor forelder er kopiert.
Steg 5:
Oppsummering:
=> Skal ikke vise fnr på kopiert forelder

src/barnetilsyn/BarnetilsynInformasjon.tsx
Feilmelding i prod på at årsakenslig er undefined som mest sannsynlig kommer av at bruker ikke har sendt inn en søknad tidligere.
=> Sjekk om forrige søknad finnes før det sjekkes på språk

src/helpers/steg/forelder.ts
Slik at søknaden kan fylles ut på engelsk.
=> ikkeOppgittAnnenForelderBegrunnelse mangler validering på engelsk. Må være med slik at man kan komme videre.

src/søknad/steg/1-omdeg/sivilstatus/Sivilstatus.tsx
Datoer nulles ut selv om det ikke gjøres noen endringer i søknaden etter gjenbruk, og søknaden blir dermed ikke auto-utfylt, selv om informasjonen finnes.
=> Ikke null ut sivilstand-datoer ved gjenbruk

src/overgangsstønad/steg/4-barnasbosted/BarnasBosted.css, src/søknad/steg/4-barnasbosted/OmAndreForelder.tsx
Har Gjort om til å bruke TextFieldMedBredde for at det skal være mer konsistent med resten av søknaden. Har fjernet styling som ikke lenger blir brukt. Bredden var satt 400px som var bredere enn mobilskjerm, det så derfor ikke noe bra ut.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-18248)
Bilde av slik det er nå:
Slik det var før:
=> Tekstfelt skal ikke være brede enn mobilskjerm bredde

src/søknad/steg/4-barnasbosted/BarnasBostedInnhold.tsx, src/søknad/steg/4-barnasbosted/BarnetsBostedEndre.tsx, src/utils/søknad.ts
Endret på sjekken erBarnetilsynSøknad for å gjøre den mer korrekt, søkerFraBestemtMåned er optional og kan derfor mangle fra søknad. Tar med søknad som prop fordi den inneholder oppdatert state og har derfor verdiene som det blir sjekket på.
Før: 
Nå:
=> Skal ikke vise annen foreldre knapper hvis det ikke er valgt barn å kopiere fra

README.md
=> Oppdaterer readme etter overgang fra å hente tokenet i cookie til å bruke fakedings

src/components/EøsIdent.tsx, src/language/tekster_en.ts, src/language/tekster_nb.ts, src/søknad/steg/1-omdeg/medlemskap/Utenlandsopphold.tsx, src/utils/søknad.ts
Tidligere fungerte ikke tekstene i utenlandsopphold, og den fungerte ikke så bra på engelsk:
Også lagt til en funksjon (hentTekstMedVariabel) som håndterer både oversettelse og tillater variabler i streng. Denne kan på sikt brukes slik at tekst-håndtering blir konsekvent i repoet, da det nå skjer på mange forskjellige måter
=> Fikse utenlandsopphold tekst

src/arbeidssøkerskjema/SkjemaApp.tsx, src/arbeidssøkerskjema/innsending/api.ts, src/arbeidssøkerskjema/steg/2-Oppsummering.tsx
Legge til arbeidsøkerskjema i ny flyt. 
- Egen funksjon `SendInnArbeidssøkerSkjemaFamiliePdf` for å bruke vår nye flyt (søknadskvittering)
- feature toggle for å bruke ny eller eksisterende flyt
=> legge til arbeidssøker søknad i ny modernisert flyt. med feturetoggle

src/components/forside/TidligereInnsendteSøknaderAlert.tsx
Vi har fått avklart tekster for tidligere innsendt søknad varsel. Derfor introduserer denne PRen nye endringer til alerten der vi nå viser når sist innsendte søknad var mottatt (per stønadstype), linker til ettersending (per stønadtype) og linker til kontakt oss (samme for alle). 
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-23469).
* Lenkene går direkte mot ekstern. Kunne være fint å ha de peke mot de respektive miljøene, men ser at det linkes ut mot eksternt andre steder i repoet, så tenker det er greit.
* Har testet og sjekket at lenkene fungerer og peker riktig per stønadsflyt.
=> Feature - søknadsflyten formidler når sist innsendte søknad var mottatt, samt lenker til eksterne resurser

src/components/forside/TidligereInnsendteSøknaderAlert.tsx
Vi må støtte flere språk. Derfor støtter vi nå Engelsk og Nynorsk.
=> Feature - tidligere innsendt søknad varsel støtter nå Engelsk og Nynorsk

src/barnetilsyn/BarnetilsynContext.tsx, src/barnetilsyn/models/søknad.ts, src/barnetilsyn/steg/8-dokumentasjon/SendBarnetilsynSøknad.tsx, src/context/SøknadContext.tsx, src/language/tekster_en.ts, src/models/søknad/søknad.ts, src/skolepenger/SkolepengerContext.tsx, src/skolepenger/models/søknad.ts, src/skolepenger/steg/7-dokumentasjon/SendSkolepengerSøknad.tsx
Ved valg av språk dukker ikke forventet språk opp i søknadskvitteringen. Dette kan skyldes at locale aldri var sendt med for barnetilsyn og skolepenger søknader. Vi sender nå med denne verdien og mange av de labelene i kvitteringen er nå på riktig språk. 
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24127).
Vi har kun testet ved å sjekke kvitteringene for søknadene i pre-prod. Det er fortsatt noen labels som feiler, men dette skyldes andre årsaker. Dette er en gradvis-fiks av label korrigering.
=> Bug - søknader for barnetilsyn og skolepenger sender nå med locale

src/arbeidssøkerskjema/innsending/api.ts, src/arbeidssøkerskjema/steg/2-Oppsummering.tsx, src/barnetilsyn/steg/8-dokumentasjon/SendBarnetilsynSøknad.tsx, src/innsending/api.ts, src/models/søknad/toggles.ts, src/overgangsstønad/steg/8-dokumentasjon/SendSøknad.tsx, src/skolepenger/steg/7-dokumentasjon/SendSkolepengerSøknad.tsx
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24467)
- Fjernet feature-toggle for styring av om man skal sende inn søknad via ny vs. gammel flyt
- Fjernet gamle endepunkt
=> skal fjerne feature-toggle for gammel vs. ny innsendingsflyt

server/routes.ts
Det har kommet nye endringer til path-to-regex i Express Middleware. Se nye endringer [her](https://github.com/pillarjs/path-to-regexp#errors). Derfor fjerner vi endepunktet da det ikke har blit kallt de siste 6 månedene. (sjekket logger)
=> Forsøker å fikse nye regex regler for path-to-regex endringer i Express

src/barnetilsyn/BarnetilsynContext.tsx, src/barnetilsyn/models/mellomlagretSøknad.ts, src/barnetilsyn/models/søknad.ts, src/barnetilsyn/steg/1-omdeg/OmDeg.tsx, src/barnetilsyn/steg/2-bosituasjon/Bosituasjon.tsx, src/barnetilsyn/steg/6-barnepass/Barnepass.tsx, src/barnetilsyn/steg/6-barnepass/hjelper.ts, src/barnetilsyn/steg/8-dokumentasjon/Dokumentasjon.tsx, src/barnetilsyn/steg/8-dokumentasjon/SendBarnetilsynSøknad.tsx, src/helpers/steg/omdeg.ts, src/søknad/steg/4-barnasbosted/BarnasBostedInnhold.tsx, src/søknad/steg/4-barnasbosted/BarnetsBostedEndre.tsx, src/utils/søknad.ts
- renamer `ISøknad` til `SøknadBarnetilsyn` 
- renamer `IMellomlagretBarnetilsynSøknad` til `MellomlagretSøknadBarnetilsyn`
For bedre lesbarhet
=> renamer interface for søknad til barnetilsyn for bedre lesbarhet

src/language/tekster_en.ts, src/language/tekster_nb.ts, src/language/tekster_nn.ts
| Etter | Før |
|-----|-------|
| ![før](https://github.com/user-attachments/assets/ee1e9639-5f3a-4a90-8bae-975fb0387549) | ![etter](https://github.com/user-attachments/assets/f579ed2a-f4bc-4046-9919-b005ba5d1ed2) |
Grunnet en refaktorering av overgangstønad type en liten stund tilbake har verdien for typen endret seg fra lowercase til uppercase. Dette ødelegger henting av alert tekst. Dette er nå fikses og burde vise riktig beskrivelse. 
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-25412).
Har bare testet i pre-prod med skolepenger.
=> Fikser alert beskrivelse for dokumentasjonsbehov for mål med utdanning

config/webpack.build.js, config/webpack.run.js
Legger til chill mode for es-lint slik at man kan forholde seg til ubrukte variabler og imports under aktiv utvikling
Favro [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-25584).
=> Legger til chill mode for es-lint slik at man kan forholde seg til ubrukte variabler og imports under aktiv utvikling

src/søknader/felles/steg/1-omdeg/OmDeg.tsx, src/søknader/felles/steg/1-omdeg/personopplysninger/Personopplysninger.tsx, src/søknader/felles/steg/1-omdeg/personopplysninger/PersonopplysningerVisning.tsx, src/søknader/felles/steg/1-omdeg/personopplysninger/SøkerBorIkkePåAdresse.tsx
Prøver å introdusere større endringer stykkevis. Derfor prøver denne PRen å fjerne feltgruppe og komponent gruppe og heller bruke native `VStack` og `Alert`. 
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-25952).
* Har testet i preprod ved å trykke rundt
* Har testet med person som har adresse beskyttelse - dette gjøres fordi jeg gjemmer adresse heading om adressen er tom.
=> Personopplysninger - fjern komponent og feltgruppe, legge til visning kondisjonal for spørsmål.

src/helpers/steg/omdeg.ts
Under testing fant man en bug der bruker kunne gå videre i medlemskap seksjonen av om deg steget. Dette skjedde når:
Bruker svarer ja på "Oppholder du og barnet/barna dere i Norge?" og ja på "Har du oppholdt deg i Norge de siste 5 årene?" for å så endre til nei på "Oppholder du og barnet/barna dere i Norge?". Bruker fikk muligheten til å trykke på neste og gå videre til neste steg uten å velge verdi for oppholdsland.
<table>
<tr>
<th style="text-align:center">Før</th>
<th style="text-align:center">Etter</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/8f8617cf-78de-4553-8f91-1f35ba10993c" alt="Før" width="400"/></td>
<td><img src="https://github.com/user-attachments/assets/2297ad71-0e6f-478e-b1ad-561a4b69b58f" alt="Etter" width="400"/></td>
</tr>
Oppgaven og …
=> Fikser bug som lot bruker gå videre uten oppholdsland verdi

src/components/dato/PeriodeDatovelger.tsx, src/søknader/barnetilsyn/steg/6-barnepass/BarnepassSpørsmål.tsx, src/søknader/felles/steg/1-omdeg/medlemskap/Utenlandsopphold.tsx, src/søknader/felles/steg/5-aktivitet/utdanning/NårSkalDuElevEllerStudent.tsx
Jobber med å utbedre større endringer, ønsker derfor å fjerne komponent gruppe og felt gruppe fra steder der dette er brukt. PeriodeDatovelger bruker nå native Aksel, samt fjerner styled div og komponent/feltgruppe. Vi bruker nå også en direkte alert på feilmelding.
<table>
<tr>
<th style="text-align:center">Før</th>
<th style="text-align:center">Etter</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/6e9f2b6a-1b59-42ee-bcd8-5c3837d7911f" alt="Før" width="400"/></td>
<td><img src="https://github.com/user-attachments/assets/374f1e77-35d9-4514-941f-364a5cfddda4" alt="Etter" width="400"/></td>
</tr>
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-26030).
* Har kun testet i …
=> PeriodeDatovelger bruker nå native Aksel

src/components/EøsIdent.tsx, src/søknader/felles/steg/1-omdeg/medlemskap/PeriodeBoddIUtlandet.module.css, src/søknader/felles/steg/1-omdeg/medlemskap/PeriodeBoddIUtlandet.tsx, src/søknader/felles/steg/1-omdeg/medlemskap/Utenlandsopphold.tsx
Jobber med å utbedre større endringer, ønsker derfor å fjerne komponent gruppe og felt gruppe fra steder der dette er brukt. Utenlandsopphold bruker nå native Aksel, samt fjerner styled div og komponent/feltgruppe.
<table>
<tr>
<th style="text-align:center">Før</th>
<th style="text-align:center">Etter</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/33775328-5655-45e4-99b0-d200d03442b7" alt="Før" width="400"/></td>
<td><img src="https://github.com/user-attachments/assets/5c140c03-aef9-4871-bf6d-a49d5482b80d" alt="Etter" width="400"/></td>
</tr>
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-26031).
* Har kun testet i pre-prod.
* Har testet med mobil og passet på at ting …
=> Utenlandsopphold bruker nå native Aksel og visningkondisjonal

src/søknader/arbeidssøkerskjema/SkjemaApp.tsx, src/utils/autentiseringogvalidering/autentisering.ts
Forsøker å introdusere små endringer i håp om å gjøre søknadsdialogen litt enklere og bedre. Ved start mot pre-prod får vi en warning i konsollen der ESLint formidler at fetchToggles mangler et dependency array. IntelliJ formidler også at vi ikke tar i bruke promisene for metoder som `verifiserAtBrukerErAutentisert`. Prøver derfor å utbedre dette slik at det blir rikig i henhold til TS konvensjoner. 
Typisk warning vi får er:
```
WARNING in [eslint] 
/Users/Kristian.Kofoed/IdeaProjects/familie-ef-soknad-frontend/src/søknader/arbeidssøkerskjema/SkjemaApp.tsx
67:6  warning  React Hook useEffect has a missing dependency: 'fetchToggles'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
✖ 1 problem (0 errors, 1 warning)
```
Denne endringen fjerner warnings siden …
=> Fikser fetchToggles warning fra ESLint
