Dockerfile
nais-dev.yaml
nais-prod.yaml
package.json
public/index.html
src/App.tsx
src/Environment.ts

Yaaasss
**https://nav.no/familie/alene-med-barn** peker nå til nais-clusterene, så vi kan legge inn nye apper under her :) Man kommer til appen, men blir stoppet og ser kun dekoratør. Dette er kanskje pga innlogging? 
Når vi eksponerer ut i prod blir det ekstra viktig at vi er obs på hva vi har toggle på og å synliggjøre at dette er under arbeid :)

Nye ingresser 

---

src/innsending/api.ts

Implisitt at post søknad er innsending?

Endre api-endepunkt

---

src/components/gruppe/KomponentGruppe.tsx

Fikser feil: KomponentGruppe.tsx exporterer FeltGruppe

---

src/arbeidssøker/ArbeidssøkerApp.tsx
src/arbeidssøker/Kvittering.tsx
src/arbeidssøker/Oppsummering.tsx
src/arbeidssøker/routes/Routes.tsx
src/arbeidssøker/side/Side.less
src/arbeidssøker/side/Side.tsx

Tomme sider for Spørsmål, Kvittering og Oppsummering er lagt til, med routing mellom dem. Løser https://favro.com/organization/98c34fb974ce445eac854de0/62dc512fcd343acab1c4424a?card=Tea-969 og https://favro.com/organization/98c34fb974ce445eac854de0/62dc512fcd343acab1c4424a?card=Tea-1042

Legg til alle sidene og routing mellom dem

---

src/arbeidssøkerskjema/Oppsummering.less
src/arbeidssøkerskjema/Oppsummering.tsx
src/arbeidssøkerskjema/Spørsmål.tsx
src/index.less
src/language/tekster.ts

Legg til oppsummering på nytt skjema

---

package-lock.json
src/arbeidssøkerskjema/Kvittering.tsx
src/arbeidssøkerskjema/side/Side.less
src/arbeidssøkerskjema/side/Side.tsx
src/index.less
src/language/tekster.ts

- Alert med klokkeslett og dato når man havner på siden
- Tekst og riktige lenker

Legger til kvitteringsside

---

src/arbeidssøkerskjema/SkjemaApp.tsx
src/arbeidssøkerskjema/SkjemaContext.tsx
src/arbeidssøkerskjema/steg/1-Spørsmål.tsx
src/arbeidssøkerskjema/steg/2-Oppsummering.tsx
src/arbeidssøkerskjema/steg/3-Kvittering.tsx

- Denne endringen forkastes dersom vi bestemmer oss for å legge på innsendingsdato via api i stedet :)
EDIT:
- Det er bestemt at innsendingsdato skal hentes fra api. Så denne PR-en vil nå inneholde endringer for å hente og vise LocalDate fra api på kvitteringssiden

Legg til innsendingsdato

---

src/arbeidssøkerskjema/Forside.less
src/arbeidssøkerskjema/Forside.tsx
src/arbeidssøkerskjema/SkjemaApp.tsx
src/language/tekster.ts

Ble litt rot med BlockContent-rendringa av teksten som var hentet fra Sanity her, så jeg la inn disclaimer-teksten rett i appen foreløpig.

Fiks styling på disclaimer

---

public/index.html

@TuvaSverdstad ga tommel opp for @charliemidtlyng  sitt[ forslag ](https://nav-it.slack.com/archives/G012YEK9YQ1/p1588767404222200):)

Endrer beskrivelse

---

src/arbeidssøkerskjema/Forside.less
src/arbeidssøkerskjema/side/Side.less

Denne setter maksbredden til innholdet til 588px.
Relatert til [denne Favro-oppgaven](https://favro.com/organization/98c34fb974ce445eac854de0/62dc512fcd343acab1c4424a?card=Tea-1088).

Fiks bredde

---

src/arbeidssøkerskjema/komponenter/StyledKnapper.tsx
src/arbeidssøkerskjema/side/Side.less
src/arbeidssøkerskjema/steg/2-Oppsummering.tsx

- Midtstiller knapper
- Legger til litt padding nederst på siden (la merke til at det ble ganske trangt når de funksjonelle tok en gjennomgang spesielt på kvitteringssiden)

Midtstill knapper

---

src/arbeidssøkerskjema/side/Side.less
src/arbeidssøkerskjema/steg/3-Kvittering.tsx
src/components/Hjelpetekst.tsx
src/language/tekster.ts
src/søknad/steg/5-aktivitet/arbeidssøker/ArbeidssøkerConfig.ts

Inneholder:
- [Legg til alerttekst](https://favro.com/organization/98c34fb974ce445eac854de0/62dc512fcd343acab1c4424a?card=Tea-1120)
- [Oppdatere hjelpetekst om 1 times reisevei](https://favro.com/organization/98c34fb974ce445eac854de0/62dc512fcd343acab1c4424a?card=Tea-1128)
- [Oppdatere hjelpetekst om registrering som arbeidssøker](https://favro.com/organization/98c34fb974ce445eac854de0/62dc512fcd343acab1c4424a?card=Tea-1129)
- Legge til beskrivelse på kvitteringsside om tilleggstønader
- Legger til litt avstand mellom listeelementene etter feedback fra Tuva

Legg til/oppdater diverse alert - og hjelpetekster

---

src/helpers/omdeg.ts
src/language/tekster.ts
src/models/steg/omDeg/sivilstatus.ts
src/søknad/SendSøknad.tsx
src/søknad/steg/1-omdeg/sivilstatus/SivilstatusConfig.tsx
src/søknad/steg/1-omdeg/sivilstatus/begrunnelse/SøknadsBegrunnelse.tsx

- Fjerner fritekstfelt for søknadsbegrunnelse
- Endrer feltnavn fra `BegrunnelseForSøknad`til `årsakEnslig`

årsak enslig og annet felt

---

craco.config.js
package-lock.json
src/arbeidssøkerskjema/side/Side.less
src/arbeidssøkerskjema/side/Side.tsx
src/assets/SendSøknadSVG.tsx
src/components/side/Side.less
src/components/side/Side.tsx
src/language/tekster.ts
src/models/søknad.ts
src/routing/Routes.tsx
src/søknad/Søknadsdialog.tsx
src/søknad/steg/9-kvittering/DineSaker.tsx
src/søknad/steg/9-kvittering/Kvittering.tsx
src/søknad/steg/9-kvittering/RegistrerDegSomArbeidssøker.tsx
src/søknad/steg/9-kvittering/TilleggsstønaderArbeidssøker.tsx
src/søknad/steg/9-kvittering/TilleggsstønaderHarAktivitet.tsx
src/søknad/steg/9-kvittering/TilleggsstønaderUnderUtdanning.tsx

**Innhold:** ✨ 
- Legger til Kvitteringskomponent
- Viser tekst, lenker og knapper basert på brukers aktivitetsvalg
- Legger til riktige lenker
- Legger til ikon på kvitteringsside

Kvittering

---

src/language/tekster.ts
src/søknad/steg/3-barnadine/LeggTilBarnFødt.tsx

Fiks label

---

src/language/tekster.ts

Endrer noen tekster
[Favro-kort](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1279)

Tekstfikser

---

package-lock.json

Fikser dependabot security issue. 
Websockets i package-lock.json.

Oppdaterer package.json

---

src/helpers/forelder.ts
src/søknad/steg/1-omdeg/medlemskap/MedlemskapConfig.tsx

Dersom man ikke kan oppgi annen forelder og man enten har valgt "Donorbarn" eller "Annet" og fylt inn begrunnelse, skal "Neste"-knappen vises og ingen flere spørsmål dukke opp.
Fjernet også en hjelpetekst på steg 1 i denne PRen.
Favro-oppgaver: 
[Steg 4 - Donorbarn](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1244)
[Steg 4 - Kan ikke oppgi den andre forelder](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1239)
[Steg 1 - "Har du bodd i Norge de siste tre årene?"
Skal ikke ha hjelpetekst](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1189)

Steg 4 – Vis "Neste" om man ikke kan oppgi annen forelder.

---

src/arbeidssøkerskjema/steg/3-Kvittering.tsx
src/components/feil/Feilside.tsx
src/søknad/steg/8-dokumentasjon/Dokumentasjon.tsx
src/søknad/steg/9-kvittering/Kvittering.tsx

Printer JSON på innsendingssiden, kvitteringssiden og Feilmelding-siden.

Print JSON for enklere feilsøking under testing

---

src/language/tekster.ts
src/søknad/steg/1-omdeg/personopplysninger/Personopplysninger.tsx
src/søknad/steg/1-omdeg/sivilstatus/Sivilstatus.tsx
src/søknad/steg/1-omdeg/sivilstatus/SivilstatusConfig.tsx

- [ Flytt sivilstatusinfo og endre ordlyd på spm](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1295)
- [Legg til hjelpetekst](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1294)
- [Endre tlfnr etter at det er skrevet inn](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1266)

Diverse fix/steg 1

---

src/Environment.ts
src/utils/autentisering.ts

Mini endring - bruk fnr i subject på localhost så innsending ikke feiler validerer i api.
(testet i preprod -login fungerer)

Flytt ? i url til env -> bruk subject i loginUrl for localhost env.

---

src/søknad/steg/3-barnadine/LeggTilBarnFødt.tsx

Slik at bruker ikke må skrive inn navn på barnet for å gå videre.
Navn på barn skl være optional.

Vis ident/fødselsdato felt samtidig som navn-felt

---

package-lock.json
src/components/filopplaster/Filopplaster.tsx
src/context/SøknadContext.tsx
src/helpers/steg/dokumentasjon.ts
src/models/dokumentasjon.ts
src/models/vedlegg.ts

Merges etter att My merget sin branch
https://github.com/navikt/familie-ef-soknad/pull/188

Dokumentasjon label

---

src/helpers/standardSvar.ts
src/helpers/svar.ts
src/søknad/steg/1-omdeg/personopplysninger/PersonopplysningerConfig.tsx
src/søknad/steg/1-omdeg/sivilstatus/SivilstatusConfig.tsx
src/søknad/steg/3-barnadine/BarneConfig.tsx
src/søknad/steg/3-barnadine/LeggTilBarn.tsx
src/søknad/steg/4-barnasbosted/ForeldreConfig.tsx

Hvis bruker legger til et ufødt barn skal de bes om å dokumentere terminbekreftelse på dokumentasjonssiden. 
[Favro-kort](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-915)

Dokumentasjonsbehov for ufødt barn

---

src/components/filopplaster/Filopplaster.tsx
src/components/spørsmål/JaNeiSpørsmålMedNavn.tsx
src/language/tekster.ts
src/søknad/steg/4-barnasbosted/BarnetsBostedEndre.tsx
src/søknad/steg/4-barnasbosted/SkalBarnetBoHosSøker.tsx
src/søknad/steg/4-barnasbosted/bostedOgSamvær/BorForelderINorge.tsx
src/søknad/steg/4-barnasbosted/bostedOgSamvær/BostedOgSamvær.tsx
src/søknad/steg/4-barnasbosted/bostedOgSamvær/HarForelderAvtaleOmDeltBosted.tsx
src/søknad/steg/4-barnasbosted/bostedOgSamvær/HarForelderSkriftligSamværsavtale.tsx
src/søknad/steg/4-barnasbosted/ikkesammeforelder/BoddSammenFør.tsx
src/søknad/steg/4-barnasbosted/ikkesammeforelder/BorAnnenForelderISammeHus.tsx
src/søknad/steg/4-barnasbosted/ikkesammeforelder/HvorMyeSammen.tsx
src/utils/barn.ts

**Steg 4 - Barnas bosted og foreldresamvær**
- Hvis barnet er født, bruk navn hentet fra TPS i stedet for [0]. 
- Hvis barnet ikke er født, bruk "barnet". 
**Innhold:**
- Ny komponent for JaNeiSvar (JaNeiSvarMedNavn) slik at vi kan tweake tekstene før de vises. Gjør det på den lette måten, bør kanskje generalisere JaNeiSvar senere enn å bruke tekstid knyttet til spm. 🤷 
- Utskiftning av JaNeiSvar til JaNeiSvarMedNavn
- Ny util for å hente ut spørsmåltekst skiftet med navn / "barnet"

Fletting av navn

---

src/models/steg/omDeg/sivilstatus.ts
src/søknad/steg/1-omdeg/sivilstatus/begrunnelse/SøknadsBegrunnelse.tsx
src/søknad/steg/2-bosituasjon/OmSamboerenDin.tsx

Løser [Steg 1 - "Hvorfor er du er alene med barn?", alternativ "Samlivsbrudd fra noen andre": Legge til navn og fødselsnummer for tidligere samboer](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1061)

Felter for å legge til informasjon om tidligere samboer ved samlivsbrudd

---

src/søknad/steg/6-meromsituasjon/NårSøkerDuOvergangsstønadFra.tsx

Skulle være 5 måneder istedenfor 2. Løser [Steg 6: Søker du fra en bestemt måned?](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1379)

Fiks "Søker fra bestemt måned"-hjelpetekst.

---

src/assets/fil.svg
src/components/AlertstripeDokumentasjon.tsx
src/søknad/steg/1-omdeg/sivilstatus/Sivilstatus.tsx
src/søknad/steg/1-omdeg/sivilstatus/begrunnelse/DatoForSamlivsbrudd.tsx
src/søknad/steg/3-barnadine/LeggTilBarnUfødt.tsx
src/søknad/steg/4-barnasbosted/bostedOgSamvær/HarForelderAvtaleOmDeltBosted.tsx
src/søknad/steg/5-aktivitet/EtablererEgenVirksomhet.tsx
src/søknad/steg/5-aktivitet/FåttJobbTilbud.tsx
src/søknad/steg/5-aktivitet/arbeidsforhold/Arbeidsgiver.tsx
src/søknad/steg/5-aktivitet/arbeidssøker/Arbeidssøker.tsx
src/søknad/steg/5-aktivitet/underUtdanning/NårSkalDuElevEllerStudent.tsx
src/søknad/steg/6-meromsituasjon/BarnMedSærligeBehov.tsx
src/søknad/steg/6-meromsituasjon/HarSøkerSagtOppEllerRedusertStilling.tsx
src/søknad/steg/6-meromsituasjon/SyktBarn.tsx
src/søknad/steg/6-meromsituasjon/SøkerErSyk.tsx
src/søknad/steg/6-meromsituasjon/SøktBarnepassOgVenterPåSvar.tsx

- [Egen Alertstripe for når man mmå legge ved dokumentasjon](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1261)

Alertstripe dokumentasjon

---

src/søknad/steg/4-barnasbosted/OmAndreForelder.tsx
src/søknad/steg/7-oppsummering/OppsummeringAktiviteter.tsx
src/søknad/steg/7-oppsummering/OppsummeringBarnaDine.tsx
src/søknad/steg/7-oppsummering/OppsummeringBarnasBosituasjon.tsx
src/søknad/steg/7-oppsummering/OppsummeringBosituasjon.tsx
src/søknad/steg/7-oppsummering/OppsummeringDinSituasjon.tsx
src/søknad/steg/7-oppsummering/OppsummeringOmDeg.tsx

Setter h-tag på overskriftene. Fikser også bugen som gjorde at det siste tallet på fødselsnummeret til annen forelder ikke kom med.

Riktig tag på Oppsummering-overskrifter

---

src/components/dato/PeriodeDatovelger.tsx
src/helpers/omdeg.ts
src/helpers/tommeSøknadsfelter.ts
src/models/periode.ts
src/models/steg/omDeg/medlemskap.ts
src/søknad/steg/1-omdeg/medlemskap/Medlemskap.tsx
src/søknad/steg/1-omdeg/medlemskap/MedlemskapConfig.tsx
src/søknad/steg/1-omdeg/medlemskap/PeriodeBoddIUtlandet.tsx
src/søknad/steg/1-omdeg/medlemskap/Utenlandsopphold.tsx

- Sletter `periodeBoddIUtlandet` hvis man endrer svar fra "Nei" til "Ja" (_Spm: Har du bodd i Norge de 3 siste årene?_)
- Setter Periodedatovelgere til default undefined (DD.MM.YYYY)
- Begrenser visning inntil du har fylt ut begrunnelse/valgt datoer

Periode datovelgere

---

src/søknad/steg/1-omdeg/sivilstatus/begrunnelse/SøknadsBegrunnelse.tsx

Løser [Kritisk: json inneholder tidligereSamboerDetaljer](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1568)

Ikke sett tidligereSamboer om det ikke er valgt

---

src/language/tekster.ts
src/søknad/steg/1-omdeg/sivilstatus/SøkerHarSøktSeparasjon.tsx
src/søknad/steg/2-bosituasjon/Bosituasjon.tsx
src/søknad/steg/4-barnasbosted/SkalBarnetBoHosSøker.tsx

Gikk gjennom innholdsdokumentet og la på der det manglet å skifte ut AlertStripeInfo med AlertSTripeDokumentasjon

Skift ut manglende AlertStripeDokumentasjon

---

src/models/steg/aktivitet/aktivitet.ts
src/søknad/steg/5-aktivitet/aksjeselskap/EgetAS.tsx

Gjør navn og arbeidsmengde i IAksjeselskap til obligatoriske

---

src/language/tekster.ts
src/søknad/steg/1-omdeg/sivilstatus/begrunnelse/DatoForSamlivsbrudd.tsx
src/søknad/steg/4-barnasbosted/SkalBarnetBoHosSøker.tsx
src/søknad/steg/6-meromsituasjon/BarnMedSærligeBehov.tsx
src/søknad/steg/6-meromsituasjon/SyktBarn.tsx
src/søknad/steg/6-meromsituasjon/SøkerErSyk.tsx
src/søknad/steg/6-meromsituasjon/SøktBarnepassOgVenterPåSvar.tsx

Løser [Gjenstående tekstfeil](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1644) og endrer tekstene på steg 6.

Tekstendring

---

src/language/tekster.ts
src/søknad/steg/1-omdeg/sivilstatus/begrunnelse/SøknadsBegrunnelse.tsx
src/søknad/steg/4-barnasbosted/ForeldreConfig.tsx

Fjerner i tillegg ubrukt tekst

Fiks bug som gjorde at man ikke kunne gå videre

---

package-lock.json
package.json
src/søknad/forside/Forside.less
src/søknad/forside/Forside.tsx
src/søknad/forside/Forsideinformasjon.tsx

Ved bruk av IE så vises feilmelding og man får ikke startet søknaden.

Hindre bruk av IE

---

src/Environment.ts
src/mock/initialState.json
src/mock/mockPerson.json
src/mock/mockPersonUtenBarn.json
src/models/person.ts
src/søknad/steg/1-omdeg/personopplysninger/Personopplysninger.tsx

(og send inn)
løser https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1562

Vis poststed og postnummer 

---

src/søknad/steg/7-oppsummering/OppsummeringBarnasBosituasjon.tsx

Løser [STEG 7 - Oppsummering - Barnas bosted.](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1536)

Fjern 'Kan ikke oppgi annen forelder' fra oppsummering

---

src/søknad/steg/7-oppsummering/OppsummeringBarnasBosituasjon.tsx
trigger-workflow

Fjern kanIkkeOppgiAnnenForelderFar fra oppsummering

---

public/index.html
src/components/spørsmål/CheckboxSpørsmål.tsx
src/components/spørsmål/JaNeiSpørsmål.tsx
src/components/spørsmål/MultiSvarSpørsmål.tsx

Legger til trackingkode for Google Tag Manager.

Google tag manager

---

src/søknad/steg/5-aktivitet/arbeidssøker/Arbeidssøker.tsx

Fjerner også kanSkaffeBarnepassInnenEnUke fra søknad.

Fjern barnepass-spørsmål fra søknad

---

README.md
src/søknad/steg/5-aktivitet/underUtdanning/UnderUtdanning.tsx
src/utils/spørsmålogsvar.ts

Validerer feltet om arbeidsmengde når man har valgt "Deltidstudie" slik at man må skrive inn et tall som er høyere enn 0 før neste seksjon dukker opp.

Deltidsstudie

---

src/barnetilsyn/steg/3-barnadine/BarnMedISøknad.tsx
src/barnetilsyn/steg/3-barnadine/BarnaDine.tsx
src/barnetilsyn/steg/4-barnasbosted/BarnasBosted.tsx
src/barnetilsyn/steg/5-aktivitet/Aktivitet.tsx
src/barnetilsyn/steg/6-barnepass/Barnepass.tsx
src/barnetilsyn/steg/6-barnepass/BarnepassSpørsmål.tsx
src/helpers/steg/barn.ts
src/language/tekster.ts
src/models/barn.ts
src/søknad/steg/3-barnadine/LeggTilBarn.tsx
src/utils/søknad.ts

Bytte medISøknad med skalHaBarnepass.
Noen småjusteringer i tillegg.

Bytte ut medISøknad til skalHaBarnepass for mer tydelig navngivning

---

src/barnetilsyn/steg/6-barnepass/BarnepassBeløp.tsx
src/barnetilsyn/steg/6-barnepass/BarnepassSpørsmål.tsx
src/barnetilsyn/steg/6-barnepass/hjelper.ts
src/components/gruppe/InputLabelGruppe.tsx
src/language/tekster.ts
src/utils/feltvalidering.ts

Løser disse:
- Kan velge annet enn tall som beløp: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1828
- Datoer frem i tid: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1832

Bugfix/datoer og gyldig beløp

---

src/barnetilsyn/steg/5-aktivitet/Aktivitet.tsx
src/barnetilsyn/steg/5-aktivitet/AktivitetOppfølgingSpørsmål.tsx
src/helpers/steg/aktivitet.ts
src/helpers/steg/aktivitetvalidering.ts
src/language/tekster.ts
src/models/steg/aktivitet/aktivitet.ts
src/models/steg/aktivitet/firma.ts
src/overgangsstønad/steg/9-kvittering/Kvittering.tsx
src/søknad/steg/5-aktivitet/AktivitetOppfølgingSpørsmål.tsx
src/søknad/steg/5-aktivitet/Firma/OmFirmaeneDine.tsx
src/søknad/steg/5-aktivitet/Firma/OmFirmaetDitt.tsx
src/søknad/steg/6-meromsituasjon/SituasjonUtil.ts
src/søknad/steg/7-oppsummering/OppsummeringAktiviteter.tsx

Ble en del endringer fra firma til firmaer - gjenbrukt samme logikk som arbeidsforhold. 
Skal være støttet i backend, men må teste det i preprod før evt. merge

Skal støtte at brukeren kan sende inn en liste av firmaer

---

src/innsending/api.ts
src/language/tekster.ts
src/skolepenger/Søknadsdialog.tsx
src/skolepenger/steg/6-oppsummering/Oppsummering.tsx
src/skolepenger/steg/7-dokumentasjon/Dokumentasjon.tsx
src/skolepenger/steg/7-dokumentasjon/SendSkolepengerSøknad.tsx
src/skolepenger/steg/8-kvittering/Kvittering.tsx
src/søknad/steg/5-aktivitet/AktivitetConfig.tsx
src/søknad/steg/5-aktivitet/underUtdanning/NårSkalDuElevEllerStudent.tsx
src/søknad/steg/5-aktivitet/underUtdanning/Utdanning.tsx
src/søknad/steg/7-oppsummering/OppsummeringDetaljertUtdanning.tsx
src/søknad/steg/9-kvittering/TilleggsstønaderUnderUtdanning.tsx

La inn oppsummering, dokumentasjon og kvitteringsside for skolepenger. Tvilsomt at APIet tar imot alt på riktig måte ennå, men må sjekkes nærmere i morgen.

Lagt inn Oppsummering, Dokumentasjon og Kvittering for skolepenger

---

src/language/tekster.ts
src/søknad/steg/9-kvittering/DineSaker.tsx

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1662

Legg til ekstra kvitteringstekst

---

src/language/tekster.ts

Fikser denne: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2119

Endre ordlyd på hjelpetekst

---

src/barnetilsyn/steg/5-aktivitet/AktivitetConfig.tsx
src/language/tekster.ts

Løser denne: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2041

Legg til åpen hjelpetekst

---

src/barnetilsyn/steg/6-barnepass/BarnepassSpørsmål.tsx
src/components/dato/PeriodeDatovelger.tsx
src/language/tekster.ts
src/søknad/steg/1-omdeg/medlemskap/Utenlandsopphold.less

Løser denne: 
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2040

Legg til hjelpetekst i periodedatovelger

---

src/arbeidssøkerskjema/steg/3-Kvittering.tsx
src/language/tekster.ts
src/søknad/steg/9-kvittering/TilleggsstønaderArbeidssøker.tsx
src/søknad/steg/9-kvittering/TilleggsstønaderHarAktivitet.tsx
src/søknad/steg/9-kvittering/TilleggsstønaderUnderUtdanning.tsx

Oppdaterer lenker og grunnbeløp på kvitteringssidene.

Oppdater lenker og grunnbeløp

---

src/overgangsstønad/Forside.tsx
src/overgangsstønad/steg/1-omdeg/OmDeg.tsx
src/overgangsstønad/steg/2-bosituasjon/Bosituasjon.tsx
src/overgangsstønad/steg/3-barnadine/BarnaDine.tsx
src/overgangsstønad/steg/4-barnasbosted/BarnasBosted.tsx
src/overgangsstønad/steg/5-aktivitet/Aktivitet.tsx
src/overgangsstønad/steg/6-meromsituasjon/MerOmDinSituasjon.tsx
src/overgangsstønad/steg/7-oppsummering/Oppsummering.tsx
src/overgangsstønad/steg/8-dokumentasjon/Dokumentasjon.tsx
src/overgangsstønad/steg/9-kvittering/Kvittering.tsx

Sender med team- og appnavn til amplitude, sånn det blir enklere å finne igjen.

Legg til attributter for team og app

---

craco.config.js
src/language/tekster_en.ts
src/language/tekster_nb.ts
src/language/tekster_nn.ts

Noen tekster som charlie oppdaget på kvitteringssiden.

Legg til glemte eng tekster på kvitteringssiden

---

package-lock.json
src/Environment.ts

Ønsker kun å ta i bruk gcp i preprod i første runde. 
Før vi tar inn det i prod må vi sjekke att feature-toggle er enabled og att gcp i prod er oppdatert
https://favro.com/organization/98c34fb974ce445eac854de0/d885c1cd3e763e8a5e124115?card=Tea-361
Oppdatering av prod gøres i ny oppgave:
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2866

Tar i bruk gcp i preprod

---

src/utils/amplitude.ts

Tagen 'app' ble overskrevet og satt til enonicxp.

Bruk 'applikasjon' istedenfor 'app'

---

src/language/tekster_en.ts

Fjerner norsk ord funnet av Mirja i en engelsk tekst

Fjern norsk ord i engelsk tekst

---

src/helpers/steg/omdeg.ts
src/language/tekster_en.ts
src/language/tekster_nb.ts
src/language/tekster_nn.ts
src/models/steg/omDeg/sivilstatus.ts
src/utils/sivilstatus.ts

Fra PDL kommer vi få nye verdier i sivilstand, har mappet de og lagt til de hvor jeg tenkte de skal brukes. Fint om dere tar en ekstra titt på `sivilstatus.ts`, samt tekster.
Tanken med denna var frem- og bakoverkompatibel
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2715
https://navikt.github.io/pdl/#_sivilstand

Lagt til verdier for sivilstatus fra PDL

---

src/language/tekster_nb.ts

Endre ordlyden i spørsmålet "Oppholder du deg i Norge?" til "Oppholder du og barnet/barna dere i Norge?"

Oppdater tekst

---

src/søknad/steg/6-meromsituasjon/BarnMedSærligeBehovBegrunnelse.tsx

Fikser tekstid og teks for barn med sørlige tilsynsbehov oppdaget av @charliemidtlyng.

Fiks tekstid for barn med særlige behov

---

src/barnetilsyn/steg/7-oppsummering/Oppsummering.tsx
src/overgangsstønad/steg/7-oppsummering/Oppsummering.tsx
src/skolepenger/steg/6-oppsummering/Oppsummering.tsx
src/søknad/steg/7-oppsummering/OppsummeringBarnaDine.tsx
src/søknad/steg/7-oppsummering/OppsummeringBarnasBosituasjon.tsx
src/søknad/steg/7-oppsummering/OppsummeringBosituasjon.tsx
src/søknad/steg/7-oppsummering/OppsummeringDinSituasjon.tsx
src/søknad/steg/7-oppsummering/OppsummeringOmDeg.tsx

Løser [denne](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-3230). Refaktorerte også bruken av tittel, slik det ble konsistent på tvers av oppsummeringskomponentene.

Oversettelser

---

src/Environment.ts

Reverts navikt/familie-ef-soknad#458

Revert "Bytt prod mellomlager til gcp."

---

src/barnetilsyn/steg/5-aktivitet/AktivitetConfig.tsx
src/barnetilsyn/steg/5-aktivitet/AktivitetOppfølgingSpørsmål.tsx
src/helpers/steg/aktivitet.ts
src/helpers/steg/aktivitetvalidering.ts
src/language/tekster_en.ts
src/language/tekster_nb.ts
src/language/tekster_nn.ts
src/models/steg/aktivitet/aktivitet.ts
src/søknad/steg/5-aktivitet/AktivitetConfig.tsx
src/søknad/steg/5-aktivitet/AktivitetOppfølgingSpørsmål.tsx

Se informasjon på [Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2243).

Splitt svar i to

---

src/søknad/steg/6-meromsituasjon/SituasjonUtil.ts

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-3967

Bare vis spørsmål om Sagt opp eller redusert stilling ved mindre enn 50%

---

.gitignore
src/mock/mockToggles.json
src/models/søknad/søknad.ts
src/models/søknad/toggles.ts
src/overgangsstønad/steg/8-dokumentasjon/SendSøknad.tsx

favro oppgave: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-4340

lagt til knappen for å behandle søknad i ny løsning

---

src/language/tekster_en.ts
src/language/tekster_nb.ts
src/søknad/steg/4-barnasbosted/ForeldreConfig.tsx
src/søknad/steg/4-barnasbosted/bostedOgSamvær/BostedOgSamvær.tsx
src/søknad/steg/4-barnasbosted/ikkesammeforelder/HvorMyeSammen.tsx

Viser forskjellige tekster basert på om barnet er født eller ikke. Løser [denne Favro-oppgaven](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-4326).

Vis andre tekster når barn ikke er født

---

src/overgangsstønad/steg/4-barnasbosted/BarnasBosted.tsx

Løser [denne Favro-oppgaven](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-4681).

Vis barnets navn hvis annen forelder er død

---

src/utils/dato.ts

Sjekk at verdi er satt

---

src/language/tekster_en.ts
src/language/tekster_nb.ts
src/language/tekster_nn.ts
src/søknad/steg/4-barnasbosted/ForeldreConfig.tsx
src/søknad/steg/4-barnasbosted/bostedOgSamvær/HarForelderAvtaleOmDeltBosted.tsx

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-4878

Delt fast bosted tekst endringer og fjern alert

---

src/barnetilsyn/steg/8-dokumentasjon/SendBarnetilsynSøknad.tsx
src/overgangsstønad/steg/8-dokumentasjon/SendSøknad.tsx
src/skolepenger/steg/7-dokumentasjon/SendSkolepengerSøknad.tsx
src/utils/amplitude.ts

Vil få oversikt over hvilke dokumentasjonsbehov som brukes mest/minst, mangler vedlegg eller er sendt inn før.

Amplitude dokumentasjonsbehov

---

src/søknad/steg/4-barnasbosted/BarnetsBostedEndre.tsx

Søker kommer ikke videre fra steg 4 hvis de ikke har annen forelder hentet fra pdl 😱

Legg på nullsjekk på forelder fra pdl

---

README.md
src/language/tekster_nb.ts

[Endret "Nav" til "NAV" på linje 587](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-6566). Formateringen er også "fikset", da tekstene som blir generert i Excel-arket ikke er formatert i henhold til prettier-instillingene for prosjektet. Fikset også en typo i readme.

Fiks tekst

---

src/language/tekster_nb.ts

Løser [denne oppgaven](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7187).

Oppdater tekster

---

src/components/spørsmål/MultiSvarSpørsmålMedNavn.tsx

Vi har til nå ikke logget MultiSvarSpørsmålMedNavn. Legger til logging av dette, men bruker den originale spørsmålsteksten, slik at vi ikke logger navn.

Logg anonymisert SpørsmålMedNavn

---

src/components/dato/utils.ts
src/søknad/steg/5-aktivitet/underUtdanning/NårSkalDuElevEllerStudent.tsx
src/søknad/steg/5-aktivitet/underUtdanning/UnderUtdanning.tsx

Tidligere kunne man sende inn en søknad uten svar på dette spørsmålet ved å fjerne svaret etter at man hadde svart på det neste spørsmålet. Løser problemet ved å slette det neste spørsmålet dersom datoen blir ugyldig.
Løser [denne Favro-oppgaven](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7515).

Fiks validering for spørsmålet "Når skal du være elev/student?"

---

src/barnetilsyn/steg/1-omdeg/OmDeg.tsx
src/helpers/steg/omdeg.ts
src/overgangsstønad/steg/1-omdeg/OmDeg.tsx
src/skolepenger/steg/1-omdeg/OmDeg.tsx
src/søknad/steg/1-omdeg/personopplysninger/Personopplysninger.tsx
test/steg/steg1_omdeg.js

[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7787).

Fjern telefonnummer fra søknad

---

server/routes.js

URL'en som er brukt er `innsendtsoknad?soknad=...` 
Det var feil url i https://github.com/navikt/familie-ef-soknad/pull/933,

Fiks redirect av innsendtsoknad?soknad=.. då urlen ikke inneholder slash

---

src/barnetilsyn/steg/7-oppsummering/Oppsummering.tsx
src/overgangsstønad/steg/7-oppsummering/Oppsummering.tsx
src/utils/validering/validering.ts

Legger til den samme ekstra valideringen vi har på oppsummeringssiden på Overgangsstønad, bare for Barnetilsyn, da det nylig skjedde at noen kom seg forbi valideringen her også. Løser [denne Favro-oppgaven](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9102).

Legg til ekstra validering på Barnetilsyn

---

src/language/tekster_en.ts

Fant feil i tekster (feil i excel) - har oppdatert excelfil i teams etter beste evne og endret tekster på engelsk så de stemmer med norske tekster 
Review - kan gjerne sjekke om dette henger sammen, dvs. kontrollere mot norske tekster som jeg antar er riktige. (tekster_nb.ts)

Engelske tekster: bugfix.

---

src/søknad/DokumentasjonsConfig.ts

Fikser feil dokumentasjonsbehovtekst

---

src/language/tekster_en.ts
src/language/tekster_nb.ts
src/language/tekster_nn.ts

Løser [dette kortet](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9549)

skal tydeligjøre spÃm om uformelt gift

---

mock/mocks/mockPerson.json
mock/mocks/mockPersonUtenBarn.json
src/barnetilsyn/steg/1-omdeg/OmDeg.tsx
src/mock/initialState.json
src/models/søknad/person.ts
src/overgangsstønad/steg/1-omdeg/OmDeg.tsx
src/skolepenger/steg/1-omdeg/OmDeg.tsx
src/søknad/steg/7-oppsummering/OppsummeringOmDeg.tsx

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10556

Fjerner felter som ikke brukes eller som ikke sendes fra backend

---

.env
mock/mocks/mockPerson.json
mock/mocks/mockPersonUtenBarn.json
src/barnetilsyn/models/søknad.ts
src/barnetilsyn/steg/1-omdeg/OmDeg.tsx
src/barnetilsyn/steg/7-oppsummering/Oppsummering.tsx
src/language/FormattedHtmlMessage.tsx
src/language/LocaleTekst.tsx
src/language/tekster_en.ts
src/language/tekster_nb.ts
src/language/tekster_nn.ts
src/mock/initialState.json
src/models/steg/adresseopplysninger.ts
src/models/steg/dokumentasjon.ts
src/models/steg/opplysningerOmAdresse.ts
src/models/søknad/person.ts
src/models/søknad/søknad.ts
src/overgangsstønad/steg/1-omdeg/OmDeg.tsx
src/overgangsstønad/steg/7-oppsummering/Oppsummering.tsx
src/skolepenger/models/søknad.ts
src/skolepenger/steg/1-omdeg/OmDeg.tsx
src/skolepenger/steg/6-oppsummering/Oppsummering.tsx
src/søknad/DokumentasjonsConfig.test.ts
src/søknad/DokumentasjonsConfig.ts
src/søknad/steg/1-omdeg/personopplysninger/Personopplysninger.tsx
src/søknad/steg/1-omdeg/personopplysninger/PersonopplysningerConfig.tsx
src/søknad/steg/1-omdeg/personopplysninger/SøkerBorIkkePåAdresse.tsx
src/søknad/steg/7-oppsummering/OppsummeringOmDeg.tsx
src/utils/visning.tsx

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10347

Bor på adresse meldt flytteendring

---

public/index.html

https://nav-it.slack.com/archives/G012YEK9YQ1/p1670861297194789
(Skal squashe den dårlige git - meldingen)

Fjern googletags

---

src/language/tekster_en.ts
src/language/tekster_nb.ts
src/language/tekster_nn.ts

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9733

BarnaDine skal vise info om at kun barn under 19 vises i oversikten

---

package-lock.json
package.json
public/index.html
src/App.tsx
src/components/Modal/ModalWrapper.tsx
src/components/filopplaster/Filopplaster.css
src/components/filopplaster/Filopplaster.tsx
src/overgangsstønad/steg/3-barnadine/BarnaDine.tsx
src/skolepenger/steg/3-barnadine/BarnaDine.tsx
src/søknad/steg/3-barnadine/Barnekort.tsx
src/søknad/steg/3-barnadine/LeggTilBarn.tsx

Modal nytt designsystem

---

src/helpers/steg/bosituasjon.ts
src/helpers/steg/forelder.ts
src/helpers/steg/omdeg.ts
src/søknad/steg/1-omdeg/sivilstatus/begrunnelse/NårFlyttetDereFraHverandre.tsx
src/søknad/steg/2-bosituasjon/BosituasjonSpørsmål.tsx
src/søknad/steg/2-bosituasjon/OmTidligereSamboer.tsx
src/søknad/steg/4-barnasbosted/ikkesammeforelder/BoddSammenFør.tsx

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-11032

skal kunne velge at man flytter fra sin gamle samboer i fremtiden

---

README.md
trigger-workflow

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10985

Oppdaterer readme med tokenx lenke

---

.env
src/arbeidssøkerskjema/komponenter/StyledKnapper.tsx
src/barnetilsyn/steg/3-barnadine/BarnMedISøknad.tsx
src/components/gruppe/FeltGruppe.tsx
src/components/gruppe/IdentEllerFødselsdatoGruppe.tsx
src/components/gruppe/InputLabelGruppe.tsx
src/components/gruppe/KomponentGruppe.tsx
src/components/gruppe/SeksjonGruppe.tsx
src/components/knapper/TilbakeNesteAvbrytKnapper.tsx
src/components/spørsmål/JaNeiSpørsmål.tsx
src/components/stegKomponenter/NårSøkerDuStønadFraGruppe.tsx
src/overgangsstønad/Forside.css
src/overgangsstønad/Søknadsdialog.css
src/overgangsstønad/steg/3-barnadine/BarnaDine.css
src/overgangsstønad/steg/4-barnasbosted/BarnasBosted.css
src/søknad/steg/3-barnadine/LeggTilBarn.css
src/søknad/steg/4-barnasbosted/OmAndreForelder.tsx
src/søknad/steg/8-dokumentasjon/LastOppVedlegg.tsx

En del ubrukt styling og styling som tilhører det gamle designsystemet kan ryddes vekk

Rydd ulogisk css

---

package-lock.json
package.json
src/arbeidssøkerskjema/side/Side.css
src/arbeidssøkerskjema/side/Side.tsx
src/components/side/Side.tsx
src/components/stegindikator/Stegindikator.tsx

Gjør dette for å kunne ta bort avhengigheter til det gamle designsystemet.
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-11923

Skal erstatte gammel stegindikator med selvlagd variant.

---

pull_request_template.md

Bedre PR-beskrivelser woopwoop

Legg til pr template

---

.github/workflows/build_dev.yaml
.github/workflows/build_n_deploy_dev.yaml
.github/workflows/build_n_deploy_prod.yaml
Dockerfile
server/.npmrc
server/package.json

navikt/ sin blir ikke vedlikeholdt, og det anbefales å bruke distroless som ikke har like mange sikkerhetshull
https://nav-it.slack.com/archives/C60FFACN5/p1687344001574929
https://nav-it.slack.com/archives/C71GRG335/p1687519626532689?thread_ts=1687518423.343899&cid=C71GRG335

Oppdaterer til distroless image

---

nais-dev.yaml
nais-prod.yaml
server/decorator.ts
server/package-lock.json
server/package.json

Up-to-date.
Dekoratøren har fått en ny major-versjon og må testes i preprod før prodsetting

Skal oppgradere server-avhengigheter i søknaden

---

src/barnetilsyn/BarnetilsynContext.tsx
src/barnetilsyn/steg/4-barnasbosted/BarnasBosted.tsx
src/barnetilsyn/steg/6-barnepass/BarnepassOrdninger.tsx
src/barnetilsyn/steg/6-barnepass/BarnepassSpørsmål.tsx
src/barnetilsyn/steg/6-barnepass/ÅrsakBarnepass.tsx
src/language/tekster_en.ts
src/language/tekster_nb.ts
src/language/tekster_nn.ts
src/models/søknad/søknad.ts
src/overgangsstønad/steg/4-barnasbosted/BarnasBosted.tsx
src/skolepenger/SkolepengerContext.tsx
src/skolepenger/steg/4-barnasbosted/BarnasBosted.tsx
src/søknad/steg/3-barnadine/Barnekort.tsx
src/søknad/steg/3-barnadine/LeggTilBarn.tsx
src/søknad/steg/4-barnasbosted/BarnasBostedInnhold.tsx
src/søknad/steg/4-barnasbosted/BarnetsBostedEndre.tsx
src/søknad/steg/4-barnasbosted/BarnetsBostedLagtTil.tsx
src/søknad/steg/4-barnasbosted/OmAndreForelder.tsx
src/søknad/steg/4-barnasbosted/SkalBarnetBoHosSøker.tsx
src/søknad/steg/4-barnasbosted/bostedOgSamvær/BorForelderINorge.tsx
src/søknad/steg/4-barnasbosted/bostedOgSamvær/BostedOgSamvær.tsx
src/utils/barn.ts

Opprydning av `barnasBosted` for å gjøre klart for å gjenbruke informasjon om forelder dersom flere barn har samme far/mor. 
- Laget filen `BarnasBostedInnhold` som samler mye av koden som har vært duplisert for hver søknad
- Mindre refaktorering som navnendringer for mer forklarende navn, fjerne unødvendige fragments, fjerne doble logikksjekker, lage type for funksjon brukt mange steder. 
- Fått fjernet en del kode ved å flytte logikk og useEffects lenger opp

Refaktor barnas bosted

---

Dockerfile

Har testet innsending av søknad i preprod ✅

Skal ikke bruke npm for å starte server

---

.github/workflows/build_n_deploy_prod.yaml

For å få med oss når deploy og bygg i prod feiler 💥 🐛 
Webhooken går mot #enslig-forsørger-ci-prod og er generert på https://api.slack.com/apps/AQJ3F1ZL4/incoming-webhooks

Skal poste bygg- og deployfeil i prod til slack

---

src/barnetilsyn/steg/6-barnepass/BarnepassOrdninger.tsx
src/components/spørsmål/SelectSpørsmål.tsx
src/søknad/steg/1-omdeg/medlemskap/Utenlandsopphold.tsx
src/søknad/steg/4-barnasbosted/AnnenForelderKnapper.tsx

Vi har mange warnings i søknaden fra eslint 😢, disse må fjernes
Har kun fjernet ubrukte imports som er tydelige at ikke brukes uten at man ser det

Skal fjerne ubrukte vars

---

src/App.tsx
src/arbeidssøkerskjema/Forside.tsx
src/arbeidssøkerskjema/steg/1-Spørsmål.tsx
src/assets/VeilederSnakkeboble.tsx
src/barnetilsyn/BarnetilsynApp.tsx
src/components/knapper/LenkeMedIkon.tsx
src/components/språkvelger/Språkvelger.tsx
src/skolepenger/Forside.tsx
src/skolepenger/SkolepengerApp.tsx
src/søknad/steg/1-omdeg/sivilstatus/SøkerErUgift.tsx
src/søknad/steg/4-barnasbosted/HvordanPraktiseresSamværet.tsx
src/søknad/steg/4-barnasbosted/OmAndreForelder.tsx
src/søknad/steg/4-barnasbosted/ikkesammeforelder/HvorMyeSammen.tsx
src/søknad/steg/8-dokumentasjon/LastOppVedlegg.tsx

Mange warnings i søknaden 😢 
Nå har jeg sett på feil som "enkelt" kan fikses:
- Sende inn faktisk verdi i stedet for events
- Definere props eller fjerne definisjon av props som ikke var nødvendig
Typingen av `IBarn[]` i div App-filer
Har lagd ganske bra commitmeldinger så kanskje bedre å lese commit for commit 😎

Fjern eslint warnings - unexpected any

---

src/barnetilsyn/steg/3-barnadine/BarnMedISøknad.tsx
src/barnetilsyn/steg/3-barnadine/BarnaDine.tsx
src/søknad/steg/4-barnasbosted/AnnenForelderKnapper.tsx
src/søknad/steg/4-barnasbosted/BarnetsBostedEndre.tsx
src/søknad/steg/4-barnasbosted/BarnetsBostedLagtTil.tsx

Skal definere funksjoner som tas inn som props

---

.github/dependabot.yml

* Lagt til server då den har en egen package.json
* Lagt til github actions
Fordi det er fint å få oppdatert dependencies til servern også 👀

Oppdatert dependabot

---

.github/workflows/build_dev.yaml
.github/workflows/build_n_deploy_dev.yaml
.github/workflows/build_n_deploy_prod.yaml

Ønsker at det skal være mulig å deploye

Deploy write

---

package-lock.json
src/helpers/steg/aktivitetvalidering.ts
src/søknad/steg/5-aktivitet/underUtdanning/StudieArbeidsmengde.tsx
src/søknad/steg/5-aktivitet/underUtdanning/UnderUtdanning.tsx

Hvis utdanning på deltid er valgt, ønsker vi å validere at prosent som blir studert er mindre enn 100 prosent. Nå blir det vist en alert når prosent er 100 eller mer, søker får heller ikke gå videre med søknaden før det er gjort endringer.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-1396

Ønsker å validere at utdanning på deltid er mindre enn 100 prosent

---

src/søknad/steg/1-omdeg/sivilstatus/Sivilstatus.tsx
src/søknad/steg/1-omdeg/sivilstatus/SøkerErSkilt.tsx
src/søknad/steg/1-omdeg/sivilstatus/SøkerErUgift.tsx
src/utils/sivilstatus.ts

Ønsker at søkere som er skilt skal få spørsmål "Er du gift uten at det er registrert i folkeregisteret i Norge?", har derfor laget et komponent som vises når sivilstatus er skilt.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-11518
Bildet viser at spørsmålet stilles når en bruker (lokalt) har sivilstatus som skilt.

Skilt sporsmal ekteskap

---

.github/workflows/codeql.yml

Trenger å bygge med npm i stedet for Yarn i arbeidsflyten for CodeQL.

Installerer og bygger med npm i stedet for yarn

---

package-lock.json
package.json

Lagt til babel core i package, da det er en avhengighet flere steder. Versjoner før 7.23 hadde en kritisk svakhet som gjorde at npm anbefalte å oppdatere den.

Lagt til babel core i package.json

---

src/components/panel/CheckboxPanel.tsx
src/components/panel/RadioPanel.tsx

[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-17350)

Radio- og checkbox-panel skal bruke aksels design tokens

---

.github/workflows/build_n_deploy_dev.yaml
.github/workflows/build_n_deploy_prod.yaml

Trenger permisssion til id-token for å deploye

---

.github/workflows/build_n_deploy_prod.yaml

Endret byggefiler til å bruke main.

---

.github/workflows/build_n_deploy_dev.yaml
.github/workflows/build_n_deploy_prod.yaml

Skal slutte å bruke api-key fra nais for deploy

---

src/barnetilsyn/BarnetilsynContext.tsx
src/helpers/steg/barnetsBostedEndre.ts
src/søknad/steg/4-barnasbosted/AnnenForelderKnapper.tsx
src/søknad/steg/4-barnasbosted/BarnetsBostedEndre.tsx

Skal kunne kopiere annen forelder fra PDL selv om det ikke har skjedd noen endringer på forelder

Fix kopier annen forelder

---

.gitignore

Vi ønsker ikke å laste opp .evn fil.

Skal ignorere .env fil.

---

src/barnetilsyn/steg/0.5-gjenbruk/Gjenbruk.tsx
src/barnetilsyn/steg/0.5-gjenbruk/GjenbrukKnapp.tsx
src/components/forside/FortsettSøknad.tsx
src/components/knapper/KnappLocaleTekstOgNavigate.tsx
src/utils/amplitude.ts

Ønsker å måle hvor mange som trykker på de ulike knappene på siden for gjenbruk. [Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-18193)

Amplitude målinger på gjenbruk knapper

---

.github/workflows/build_n_deploy_dev.yaml
.github/workflows/build_n_deploy_prod.yaml
config/webpack.build.js
package-lock.json
package.json

Lettere å debugge i Sentry når noe går galt i søknadsprosessen.
Ref denne som jeg trigget i preprod:
https://sentry.gc.nav.no/organizations/nav/issues/554085/?environment=preprod&project=36&query=is%3Aunresolved&referrer=issue-stream
Ser dessverre ut som vi må bruke `uploadLegacySourcemaps` for å få det til å funke med self hosted sentry

Skal ha source maps i sentry

---

src/arbeidssøkerskjema/Forside.tsx

FIX: rettet skrivefeil på Box padding props.

---

mock/mock-server.js
package.json
server/miljø.ts
src/Environment.ts

Kan nå kjøre søknaden lokalt med mock

---

src/models/søknad/toggles.ts
src/overgangsstønad/steg/7-oppsummering/Oppsummering.tsx

Vil rydde bort unødvendig kode

Vil fjerne toggle validerbosituasjon. 

---

.github/workflows/build_n_deploy_dev.yaml
.github/workflows/build_n_deploy_prod.yaml
src/søknad/steg/1-omdeg/sivilstatus/Sivilstatus.tsx

Skal ha riktig sentry-config for source map bygging

---

server/package-lock.json
server/package.json
server/proxy.ts

Ny versjon av HPM som krever noen endringer.

Oppgradere og skrive om bruk av http-proxy-middleware

---

src/language/tekster_nb.ts

Lagt til mellomrom mellom ordene har og rett.

---

package-lock.json
package.json
server/package-lock.json
server/package.json

Gjør det enklere i egen PR, den fra dependabot har fått conflict 👎

Major bump UUID

---

.github/workflows/build_n_deploy_dev.yaml
.github/workflows/build_n_deploy_prod.yaml

revert migrering til gar

---

.github/workflows/build_dev.yaml
.github/workflows/build_n_deploy_dev.yaml
.github/workflows/build_n_deploy_prod.yaml
.github/workflows/codeql.yml
.github/workflows/playwright.yml
Dockerfile
package.json
server/package-lock.json
server/package.json
server/register.ts

Skal oppgradere til node 20

---

src/language/tekster_en.ts
src/language/tekster_nb.ts
src/language/tekster_nn.ts

Vi fikk inn en Jira-task på dette: https://jira.adeo.no/browse/FAGSYSTEM-347445
Kanskje går det an å automatisere denne prosessen slik at vi slipper å glemme dette hvert år? 🤔

oppdaterer grunnbeløpet

---

src/overgangsstønad/steg/8-dokumentasjon/SendSøknad.tsx

Fjerne console log fra frontend

Fjern console log

---

src/components/forside/TidligereInnsendteSøknaderAlert.tsx
src/models/søknad/stønadstyper.ts

Revert av StønadsType til lowercase grunnet uventet oppførsel resten av appen.

Revert av StønadsType til lowercase

---

src/barnetilsyn/steg/5-aktivitet/Aktivitet.tsx

Mirja ønsker ikke at alternativer skal sendes med på dette spørsmålet

fjerne alternativer hvaErDinArbeidssituasjon

---

src/arbeidssøkerskjema/innsending/api.ts
src/components/forside/TidligereInnsendteSøknaderAlert.tsx
src/innsending/api.ts

Gjøres i forbindelse med opprydding av gammel søknadsflyt.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24467)

skal ta i bruk ny url for innsending av søknad

---

src/utils/søknad.ts

fikser url pga feil i prod

---

src/utils/søknad.ts

Utbedrer url for uthenting av forige barnetilsynsøknad

---

src/App.tsx
src/components/forside/TidligereInnsendteSøknaderAlert.tsx
src/models/søknad/toggles.ts

Rydding av noen gamle featuretoggles som ikke trengs lenger.

Fjerne utgått featuretoggles

---

server/package-lock.json
server/package.json
server/routes.ts
server/server-lokal.ts
server/server.ts
server/tokenProxy.ts

Bump express major

---

src/søknader/felles/steg/1-omdeg/OmDeg.tsx
src/søknader/felles/steg/1-omdeg/OmDegContext.tsx
src/søknader/felles/steg/1-omdeg/OmDegValidering.ts
src/søknader/felles/steg/1-omdeg/sivilstatus/Sivilstatus.tsx
src/søknader/felles/steg/1-omdeg/sivilstatus/SpørsmålGiftSeparertEllerSkiltIkkeRegistrert.tsx
src/søknader/felles/steg/1-omdeg/sivilstatus/SøkerErGift.tsx
src/søknader/felles/steg/1-omdeg/sivilstatus/SøkerHarSøktSeparasjon.tsx
src/søknader/felles/steg/1-omdeg/sivilstatus/begrunnelse/DatoForSamlivsbrudd.tsx
src/søknader/felles/steg/1-omdeg/sivilstatus/begrunnelse/EndringISamvær.tsx
src/søknader/felles/steg/1-omdeg/sivilstatus/begrunnelse/NårFlyttetDereFraHverandre.tsx
src/søknader/felles/steg/1-omdeg/sivilstatus/begrunnelse/OmDenTidligereSamboerenDin.tsx
src/søknader/felles/steg/1-omdeg/sivilstatus/begrunnelse/ÅrsakEnslig.tsx

Koble sivilstatus på omdegkontekst

---

src/søknader/felles/steg/1-omdeg/OmDeg.test.tsx
src/søknader/felles/steg/3-barnadine/LeggTilBarnKort.tsx
src/søknader/felles/steg/3-barnadine/LeggTilBarnModal.tsx
src/søknader/overgangsstønad/steg/3-barnadine/BarnaDine.test.tsx
src/søknader/overgangsstønad/steg/3-barnadine/BarnaDine.tsx
src/test/actions.tsx
src/test/axios.ts
src/test/utils.ts
src/utils/dato.ts

Tester for barna dine

---

src/søknader/felles/steg/2-bosituasjon/BosituasjonSpørsmål.tsx
src/søknader/felles/steg/2-bosituasjon/EkteskapsliknendeForhold.tsx
src/søknader/felles/steg/2-bosituasjon/OmSamboerenDin.tsx
src/søknader/felles/steg/2-bosituasjon/OmTidligereSamboer.tsx
src/søknader/felles/steg/2-bosituasjon/SøkerSkalFlytteSammenEllerFåSamboer.tsx

tar i bruk context for bosituasjon i større grad

---

src/components/LesMerTekst.tsx
src/components/dato/MånedÅrVelger.tsx
src/components/dato/PeriodeÅrMånedvelgere.tsx
src/søknader/felles/steg/5-aktivitet/underUtdanning/TidligereUtdanning.tsx
src/søknader/felles/steg/5-aktivitet/underUtdanning/Utdanning.tsx
src/søknader/overgangsstønad/steg/5-aktivitet/Aktivitet.test.ts
src/test/axios.ts

Tester for aktivitet overgangsstønad

---

src/søknader/barnetilsyn/Forside.test.tsx
src/søknader/barnetilsyn/Søknadsdialog.tsx
src/søknader/skolepenger/Forside.test.tsx
src/test/TestContainer.tsx
src/test/axios.ts
src/test/domeneUtils.ts

Tester for andre stonader

---

src/søknader/barnetilsyn/steg/3-barnadine/BarnaDine.test.tsx
src/søknader/barnetilsyn/steg/4-barnasbosted/BarnasBosted.test.ts
src/søknader/barnetilsyn/steg/5-aktivitet/Aktivitet.test.ts
src/søknader/barnetilsyn/steg/6-barnepass/Barnepass.test.ts
src/søknader/felles/steg/1-omdeg/OmDeg.test.tsx
src/søknader/felles/steg/1-omdeg/sivilstatus/begrunnelse/OmDenTidligereSamboerenDin.test.tsx
src/søknader/felles/steg/2-bosituasjon/Bosituasjon.test.tsx
src/søknader/felles/steg/3-barnadine/BarnaDine.test.tsx
src/søknader/felles/steg/4-barnasbosted/BarnasBosted.test.ts
src/søknader/overgangsstønad/steg/5-aktivitet/Aktivitet.test.ts
src/søknader/overgangsstønad/steg/6-meromsituasjon/MerOmDinSituasjon.test.tsx
src/søknader/skolepenger/steg/5-aktivitet/UtdanningSituasjon.test.ts
src/test/actions.tsx
src/test/axios.ts
vitest.config.ts

- Fjerner overfladig stønadstype inn som et parameter nå som vi har 3 forskjellige mock-funksjoner for de tre forskjellige stønadene
- Tester for "utdanningen din"-steget i skolepenger

Tester skolepenger utdanningen din

---

src/helpers/steg/omdeg.ts
src/søknader/barnetilsyn/steg/3-barnadine/BarnaDine.test.tsx
src/søknader/barnetilsyn/steg/4-barnasbosted/BarnasBosted.test.ts
src/søknader/barnetilsyn/steg/5-aktivitet/Aktivitet.test.ts
src/søknader/barnetilsyn/steg/6-barnepass/Barnepass.test.ts
src/søknader/felles/steg/1-omdeg/OmDeg.test.tsx
src/søknader/felles/steg/1-omdeg/OmDegContext.tsx
src/søknader/felles/steg/1-omdeg/medlemskap/Medlemskap.tsx
src/søknader/felles/steg/1-omdeg/sanering.ts
src/søknader/felles/steg/1-omdeg/sivilstatus/begrunnelse/OmDenTidligereSamboerenDin.test.tsx
src/søknader/felles/steg/2-bosituasjon/Bosituasjon.test.tsx
src/søknader/felles/steg/3-barnadine/BarnaDine.test.tsx
src/søknader/felles/steg/4-barnasbosted/BarnasBosted.test.ts
src/søknader/felles/steg/8-dokumentasjon/Dokumentasjon.test.ts
src/søknader/overgangsstønad/steg/5-aktivitet/Aktivitet.test.ts
src/søknader/overgangsstønad/steg/6-meromsituasjon/MerOmDinSituasjon.test.tsx
src/søknader/skolepenger/steg/5-aktivitet/UtdanningSituasjon.test.ts
src/test/aksjoner.tsx
src/test/dato.ts

Det fantes en bug på første siden i søknaden som tillot bruker å navigere seg videre uten å ha fylt ut alle nødvendige verdier. Denne PRen utbedrer dette og legger til tester som sjekker at neste-knappen kun dukker opp ved ferdige utfylte verdier for medlemskap.
Takk til @krikof-nav for godt samarbeid 🤝

Fix logikk neste knapp om deg

---

src/components/gruppe/IdentEllerFødselsdatoGruppe.tsx
src/søknader/felles/steg/2-bosituasjon/BosituasjonSpørsmål.tsx
src/søknader/felles/steg/2-bosituasjon/EkteskapslignendeForhold.tsx
src/søknader/felles/steg/2-bosituasjon/OmSamboerenDin.tsx
src/søknader/felles/steg/2-bosituasjon/OmTidligereSamboer.tsx
src/søknader/felles/steg/2-bosituasjon/SøkerSkalFlytteSammenEllerFåSamboer.tsx
src/søknader/felles/steg/4-barnasbosted/OmAndreForelder.tsx

Planen er å introdusere de større endringene gradvis. Derfor er det fint å gå gjennom steg for steg og fjerne disse gruppene da de gir uventet padding og oppførsel på ting. Denne PRen har som mål å fjerne seksjon, komponent og feltgruppe fra komponenter som tilhører `bosituasjon`, samt forenkle kode for visning av spørsmål. 
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-26061).
* Har testet i preprod
* Har testet med mobil enhet
* Har testet med VoiceOver for å passe på at felt blir lest opp

Bosituasjon - fjerner seksjon, komponent og feltgruppe.

---

src/søknader/barnetilsyn/steg/5-aktivitet/AktivitetOppfølgingSpørsmål.tsx
src/søknader/felles/steg/5-aktivitet/AktivitetOppfølgingSpørsmål.tsx
src/søknader/felles/steg/5-aktivitet/arbeidsforhold/OmArbeidsforholdetDitt.tsx
src/søknader/overgangsstønad/Søknadsdialog.tsx
src/søknader/overgangsstønad/steg/5-aktivitet/Aktivitet.tsx
src/søknader/overgangsstønad/steg/5-aktivitet/AktivitetContext.ts

Jobber med søknadsforbedringer og prøver derfor å lage providers for de nødvendige stegene. Her prøver vi å lage en aktivitets provider for steget aktivitet for overgangsstønad steget. 
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-26308).
* Testet lokalt mot preprod, prøvd å svare hver eneste verdi.
* Sjekket at verdien holdes riktig mot kvittering og i ef-sak.
* Prøvd å gå frem og tilbake med mellomlagring.

Aktivitet provider for Aktivitet steg i overganggstønad
